"""Curated Theodore movement beats for every Food Handler Safety slide."""

from __future__ import annotations

from .driver_avatar_cues import CueRow


def _c(
    first: str,
    second: str = "explain",
    *,
    gaze: str = "learner",
    expression: str = "warm",
    intensity: float = 0.82,
) -> tuple[CueRow, ...]:
    return (
        (0.03, 0.38, first, gaze, "both" if first in {"wash-hands", "sanitize", "compare"} else "right", intensity, expression),
        (0.46, 0.34, second, "slide" if second == "point-to-slide" else "learner", "left", 0.72, expression),
        (0.84, 0.14, "transition", "learner", "none", 0.48, "encouraging"),
    )


# Ordered by module (hygiene, temps, contamination, cleaning, pathogens,
# service) and by slide index inside each module, so a beat is easy to find
# next to the slide it teaches.
FOOD_AVATAR_CUES: dict[str, tuple[CueRow, ...]] = {
    # Module 1 — hygiene and illness
    "Prep card, not accreditation": _c("caution", "point-to-slide", expression="serious"),
    "Why food handler cards matter": _c("point-to-slide", "open-palm", gaze="slide"),
    "Two-hour course map": _c("count", "point-to-slide", gaze="slide"),
    "Handwashing that works": _c("wash-hands", "count", intensity=1.0),
    "Situation: After raw chicken": _c("wash-hands", "gloves", expression="serious"),
    "Situation: Back from break": _c("phone-away", "wash-hands"),
    "Gloves done right": _c("gloves", "wash-hands"),
    "Situation: Raw then sandwich": _c("gloves", "compare", expression="serious"),
    "Bare-hand contact rules": _c("stop", "demonstrate", expression="serious"),
    "Illness reporting": _c("caution", "stop", expression="concerned"),
    "Situation: Morning stomach flu": _c("stop", "listen", expression="concerned"),
    "Big Six and exclusion": _c("count", "stop", expression="serious"),
    "Personal cleanliness": _c("count", "demonstrate"),
    "Hair, nails, and jewelry": _c("demonstrate", "count"),
    "Cuts and bandages": _c("gloves", "caution", expression="concerned"),
    "Situation: Cut finger on the line": _c("stop", "gloves", expression="concerned", intensity=1.0),
    "Ready-to-eat foods": _c("gloves", "caution"),
    "Customer allergen basics": _c("stop", "ask", expression="serious"),
    "Situation: Guest nut allergy": _c("listen", "ask", expression="concerned"),
    "Module wrap — hygiene": _c("count", "celebrate", expression="encouraging"),
    # Module 2 — temperature control
    "Temperature danger zone": _c("compare", "point-to-slide", gaze="slide", expression="serious"),
    "What counts as TCS food": _c("count", "point-to-slide", gaze="slide"),
    "Cold holding": _c("thermometer", "point-to-slide", gaze="slide"),
    "Situation: Walk-in at 48°F": _c("thermometer", "stop", expression="concerned", intensity=1.0),
    "Hot holding": _c("thermometer", "caution", expression="serious"),
    "Situation: Steam table drops": _c("thermometer", "caution", expression="concerned"),
    "Cooking poultry to 165°F": _c("thermometer", "count"),
    "Ground meats to 155°F": _c("thermometer", "compare"),
    "Whole cuts and fish 145°F": _c("thermometer", "point-to-slide", gaze="slide"),
    "Situation: Checking a burger": _c("thermometer", "stop", expression="serious"),
    "Cooling cooked food": _c("count", "thermometer"),
    "Situation: Deep pot of chili": _c("stop", "count", expression="serious"),
    "Reheating leftovers": _c("thermometer", "count", expression="serious"),
    "Thawing safely": _c("compare", "caution"),
    "Situation: Chicken on the counter": _c("stop", "compare", expression="serious"),
    "Receiving temperature checks": _c("demonstrate", "thermometer", expression="serious"),
    "Date marking": _c("count", "point-to-slide", gaze="slide"),
    "Thermometer habits": _c("thermometer", "demonstrate"),
    "Time as a public health control": _c("count", "caution", expression="serious"),
    "Module wrap — temperatures": _c("thermometer", "celebrate", expression="encouraging"),
    # Module 3 — contamination and allergens
    "Cross-contamination basics": _c("compare", "stop", expression="serious"),
    "Color-coded boards and tools": _c("compare", "point-to-slide", gaze="slide"),
    "Situation: Same knife raw then RTE": _c("stop", "sanitize", expression="serious"),
    "Clean then sanitize": _c("sanitize", "count"),
    "Sanitizer strength and strips": _c("sanitize", "thermometer"),
    "Situation: Cloudy sanitizer bucket": _c("stop", "sanitize", expression="concerned"),
    "FIFO stock rotation": _c("demonstrate", "point-to-slide", gaze="slide"),
    "Pest prevention": _c("stop", "count", expression="serious"),
    "Situation: Droppings in dry storage": _c("stop", "caution", expression="concerned", intensity=1.0),
    "Allergen cross-contact": _c("compare", "stop", expression="serious", intensity=1.0),
    "FDA Big 9 list": _c("count", "point-to-slide", gaze="slide"),
    "Situation: Shared fryer allergen": _c("compare", "stop", expression="concerned"),
    "Chemical contamination": _c("caution", "stop", expression="serious"),
    "Physical hazards": _c("caution", "demonstrate", expression="serious"),
    "Common pathogens overview": _c("caution", "point-to-slide", gaze="slide"),
    "Produce washing": _c("wash-hands", "demonstrate"),
    "Health inspections": _c("point-to-slide", "count", expression="serious"),
    "If a guest gets sick": _c("listen", "caution", expression="concerned"),
    "Situation: Inspector at the door": _c("listen", "open-palm", expression="serious"),
    "Module wrap — contamination": _c("compare", "celebrate", expression="encouraging"),
    # Module 4 — cleaning and facilities
    "Why cleaning is food safety": _c("compare", "point-to-slide", gaze="slide"),
    "Three-compartment sink": _c("count", "demonstrate"),
    "Dishmachine basics": _c("demonstrate", "thermometer"),
    "Food-contact surfaces": _c("sanitize", "compare"),
    "Situation: After raw fish prep": _c("sanitize", "count", expression="serious"),
    "Wiping cloths": _c("sanitize", "caution"),
    "Situation: Cloth left overnight": _c("stop", "sanitize", expression="concerned"),
    "Handwashing sinks stay dedicated": _c("wash-hands", "stop", expression="serious"),
    "Situation: Mop water in hand sink": _c("stop", "wash-hands", expression="concerned"),
    "Floors, walls, ceilings": _c("point-to-slide", "demonstrate", gaze="slide"),
    "Restroom readiness": _c("wash-hands", "count"),
    "Garbage and grease": _c("caution", "demonstrate", expression="serious"),
    "Water and ice safety": _c("demonstrate", "stop", expression="serious"),
    "Chemical storage": _c("caution", "stop", expression="serious"),
    "Situation: Bleach beside flour": _c("stop", "caution", expression="concerned", intensity=1.0),
    "Clean-in-place equipment": _c("demonstrate", "sanitize"),
    "Closing cleaning checklist": _c("count", "point-to-slide", gaze="slide"),
    "Who cleans what": _c("compare", "ask"),
    "Ventilation and grease": _c("caution", "point-to-slide", gaze="slide", expression="serious"),
    "Module wrap — cleaning": _c("sanitize", "celebrate", expression="encouraging"),
    # Module 5 — pathogens and high-risk guests
    "How people get sick from food": _c("count", "point-to-slide", gaze="slide", expression="serious"),
    "Bacteria, viruses, parasites, toxins": _c("count", "compare", expression="serious"),
    "Norovirus deep dive": _c("wash-hands", "stop", expression="concerned", intensity=1.0),
    "Salmonella": _c("thermometer", "caution", expression="serious"),
    "STEC and ground beef": _c("thermometer", "compare", expression="serious"),
    "Listeria and cold RTE foods": _c("thermometer", "point-to-slide", gaze="slide", expression="serious"),
    "Hepatitis A": _c("wash-hands", "stop", expression="serious"),
    "Clostridium botulinum": _c("caution", "stop", expression="serious", intensity=1.0),
    "Clostridium perfringens": _c("count", "thermometer", expression="serious"),
    "Staphylococcus aureus": _c("gloves", "wash-hands", expression="serious"),
    "High-risk populations": _c("listen", "caution", expression="concerned"),
    "Situation: Nursing home catering": _c("thermometer", "listen", expression="concerned"),
    "Symptoms to take seriously": _c("count", "caution", expression="concerned"),
    "Outbreak response basics": _c("listen", "count", expression="serious"),
    "Situation: Three guests report illness": _c("listen", "stop", expression="concerned"),
    "FAT TOM growth conditions": _c("count", "point-to-slide", gaze="slide"),
    "Spores and cooling": _c("thermometer", "count", expression="serious"),
    "Ready-to-eat contamination routes": _c("compare", "gloves", expression="serious"),
    "Prevention hierarchy": _c("count", "open-palm"),
    "Module wrap — pathogens": _c("open-palm", "celebrate", expression="encouraging"),
    # Module 6 — receiving, storage, and service
    "Approved suppliers": _c("stop", "compare", expression="serious"),
    "Receiving inspection checklist": _c("count", "thermometer"),
    "Situation: Warm dairy delivery": _c("thermometer", "stop", expression="concerned", intensity=1.0),
    "Dry storage rules": _c("count", "demonstrate"),
    "Cold storage organization": _c("compare", "point-to-slide", gaze="slide"),
    "Situation: Chicken above lettuce": _c("stop", "compare", expression="concerned"),
    "Hot holding during service": _c("thermometer", "count"),
    "Buffet and self-service": _c("demonstrate", "point-to-slide", gaze="slide"),
    "Situation: Dirty plate refill": _c("stop", "open-palm", expression="serious"),
    "Leftovers and takeout": _c("thermometer", "demonstrate"),
    "Ice scoop hygiene": _c("demonstrate", "stop", expression="serious"),
    "Situation: Scoop in the ice": _c("stop", "sanitize", expression="concerned"),
    "Service utensils and sneeze guards": _c("demonstrate", "caution"),
    "Bare hand vs utensils at service": _c("compare", "gloves", expression="serious"),
    "Closing: discard vs save": _c("compare", "count", expression="serious"),
    "Temperature logs habit": _c("thermometer", "point-to-slide", gaze="slide"),
    "Alameda inspection readiness": _c("count", "point-to-slide", gaze="slide", expression="serious"),
    "Situation: Critical violation found": _c("stop", "wash-hands", expression="concerned", intensity=1.0),
    "Finish with the official course": _c("point-to-slide", "open-palm", gaze="slide", expression="encouraging"),
    "Full course recap": _c("open-palm", "celebrate", expression="celebrating"),
}


FOOD_AVATAR_TITLES = frozenset(FOOD_AVATAR_CUES)

from .slide_keys import register_title_aliases  # noqa: E402

register_title_aliases(FOOD_AVATAR_CUES)
