// Auto-generated by scripts/generate_profile_avatars.py — do not edit.
export type AvatarStyle = "realistic" | "cute";

export type AvatarEntry = {
  id: string;
  label: string;
  style: AvatarStyle;
  alt: string;
  path: string;
  skin?: string;
  hair?: string;
  accessories?: string;
  expression?: string;
};

export const DEFAULT_AVATAR_ID = "r-nova";

export const LEGACY_AVATAR_ALIASES: Record<string, string> = {
  "": DEFAULT_AVATAR_ID,
  default: DEFAULT_AVATAR_ID,
  none: DEFAULT_AVATAR_ID,
  null: DEFAULT_AVATAR_ID,
  undefined: DEFAULT_AVATAR_ID,
  logo: "c-sunny",
  "logo-mark": "c-sunny",
  bayon: "c-sunny",
  "bayon-buddy": "c-sunny",
  mascot: "c-sunny",
  "salareen-mascot": "c-sunny",
  initials: DEFAULT_AVATAR_ID,
  emoji: "c-peach",
  graduate: "c-sunny",
  theodore: "c-moss",
  "ai-host": "c-moss",
  "presenter-male": "r-amir",
  "presenter-female": "r-sofia",
};

export const AVATAR_CATALOG: AvatarEntry[] = [
  { id: "r-nova", label: "Nova", style: "realistic", alt: "Portrait of Nova, medium-brown skin, short curly hair, round glasses", path: "/avatars/r-nova.svg", skin: "medium-brown", hair: "short curly dark brown", accessories: "round glasses" },
  { id: "r-amir", label: "Amir", style: "realistic", alt: "Portrait of Amir, deep brown skin, short fade haircut, warm smile", path: "/avatars/r-amir.svg", skin: "deep brown", hair: "short fade black", accessories: "" },
  { id: "r-mei", label: "Mei", style: "realistic", alt: "Portrait of Mei, light-medium skin, sleek bob, soft smile", path: "/avatars/r-mei.svg", skin: "light-medium", hair: "black bob", accessories: "" },
  { id: "r-sofia", label: "Sofia", style: "realistic", alt: "Portrait of Sofia, olive skin, long wavy hair, gold hoop earrings", path: "/avatars/r-sofia.svg", skin: "olive", hair: "long wavy chestnut", accessories: "gold hoops" },
  { id: "r-jordan", label: "Jordan", style: "realistic", alt: "Portrait of Jordan, fair skin with freckles, short auburn hair", path: "/avatars/r-jordan.svg", skin: "fair freckled", hair: "short auburn", accessories: "" },
  { id: "r-kai", label: "Kai", style: "realistic", alt: "Portrait of Kai, tan skin, textured coils under a soft beanie", path: "/avatars/r-kai.svg", skin: "tan", hair: "textured coils", accessories: "slate beanie" },
  { id: "r-priya", label: "Priya", style: "realistic", alt: "Portrait of Priya, warm brown skin, long dark hair with side part", path: "/avatars/r-priya.svg", skin: "warm brown", hair: "long dark side-part", accessories: "" },
  { id: "r-leo", label: "Leo", style: "realistic", alt: "Portrait of Leo, medium-dark skin, short locs, clear glasses", path: "/avatars/r-leo.svg", skin: "medium-dark", hair: "short locs", accessories: "clear glasses" },
  { id: "r-sam", label: "Sam", style: "realistic", alt: "Portrait of Sam, light skin, silver-streak short hair, kind smile", path: "/avatars/r-sam.svg", skin: "light", hair: "short silver-streak", accessories: "" },
  { id: "c-peach", label: "Peach", style: "cute", alt: "Cute avatar Peach, peachy skin, pigtails, rosy cheeks", path: "/avatars/c-peach.svg", skin: "peach", hair: "brown pigtails", accessories: "blush cheeks" },
  { id: "c-mint", label: "Mint", style: "cute", alt: "Cute avatar Mint, soft skin, mint bob hair, freckles", path: "/avatars/c-mint.svg", skin: "soft ivory", hair: "mint bob", accessories: "freckles" },
  { id: "c-coco", label: "Coco", style: "cute", alt: "Cute avatar Coco, deep brown skin, afro puffs, star hair clip", path: "/avatars/c-coco.svg", skin: "deep brown", hair: "afro puffs", accessories: "star clip" },
  { id: "c-sky", label: "Sky", style: "cute", alt: "Cute avatar Sky, light skin, blue beanie, round cheeks", path: "/avatars/c-sky.svg", skin: "light", hair: "hidden under beanie", accessories: "sky-blue beanie" },
  { id: "c-honey", label: "Honey", style: "cute", alt: "Cute avatar Honey, golden skin, messy bun, round glasses", path: "/avatars/c-honey.svg", skin: "golden", hair: "messy bun", accessories: "round glasses" },
  { id: "c-berry", label: "Berry", style: "cute", alt: "Cute avatar Berry, medium skin, curly bangs, heart hair clip", path: "/avatars/c-berry.svg", skin: "medium", hair: "curly bangs", accessories: "heart clip" },
  { id: "c-moss", label: "Moss", style: "cute", alt: "Cute avatar Moss, olive skin, short fluffy hair, headphones", path: "/avatars/c-moss.svg", skin: "olive", hair: "short fluffy", accessories: "headphones" },
  { id: "c-luna", label: "Luna", style: "cute", alt: "Cute avatar Luna, pale skin, silver hair, crescent pin", path: "/avatars/c-luna.svg", skin: "pale", hair: "silver bob", accessories: "crescent pin" },
  { id: "c-sunny", label: "Sunny", style: "cute", alt: "Cute avatar Sunny, warm brown skin, cornrows, bright smile", path: "/avatars/c-sunny.svg", skin: "warm brown", hair: "cornrows", accessories: "" },
];

export const AVATAR_IMAGES: Record<string, number> = {
  "r-nova": require("../../assets/avatars/r-nova.png"),
  "r-amir": require("../../assets/avatars/r-amir.png"),
  "r-mei": require("../../assets/avatars/r-mei.png"),
  "r-sofia": require("../../assets/avatars/r-sofia.png"),
  "r-jordan": require("../../assets/avatars/r-jordan.png"),
  "r-kai": require("../../assets/avatars/r-kai.png"),
  "r-priya": require("../../assets/avatars/r-priya.png"),
  "r-leo": require("../../assets/avatars/r-leo.png"),
  "r-sam": require("../../assets/avatars/r-sam.png"),
  "c-peach": require("../../assets/avatars/c-peach.png"),
  "c-mint": require("../../assets/avatars/c-mint.png"),
  "c-coco": require("../../assets/avatars/c-coco.png"),
  "c-sky": require("../../assets/avatars/c-sky.png"),
  "c-honey": require("../../assets/avatars/c-honey.png"),
  "c-berry": require("../../assets/avatars/c-berry.png"),
  "c-moss": require("../../assets/avatars/c-moss.png"),
  "c-luna": require("../../assets/avatars/c-luna.png"),
  "c-sunny": require("../../assets/avatars/c-sunny.png"),
};

