"""Theodore's voice lines for when a student is absent during a lesson.

Use ``{n}`` as the placeholder for the student's name.  Every bucket covers a
different moment in the absence timeline so the right tone is always available:

    immediate  →  first moment detected absent
    check_10s  →  ten seconds in
    check_30s  →  thirty seconds in
    check_60s  →  one minute in
    check_90s  →  ninety seconds in
    check_120s →  two minutes in
    boot_group →  three-minute boot message (group mode only)
    final_solo →  three-plus minutes in solo mode (never boots, waits forever)
    solo_cycle →  ongoing repeating nudges in solo mode (80+ for variety)
    welcome_back → when the participant returns
"""

from __future__ import annotations

ABSENCE_PHRASES: dict[str, list[str]] = {
    # ------------------------------------------------------------------ #
    # immediate — warm, reassuring, professional pause announcement        #
    # ------------------------------------------------------------------ #
    "immediate": [
        "We'll take a short pause while {n} steps away for a moment.",
        "No worries everyone, we're just waiting a moment for {n} to return.",
        "Let's hold here briefly while {n} gets back to us.",
        "I'm going to pause the lesson for a moment while we wait for {n}.",
        "It looks like {n} has stepped away. We'll resume as soon as they're back.",
        "We'll take a quick breather while {n} sorts something out.",
        "Holding on for {n} — we'll pick right back up once they return.",
        "Looks like {n} has stepped out. Let's wait just a moment.",
        "I see {n} has stepped away. No rush — we'll be here.",
        "Pausing briefly for {n}. Everyone else, feel free to take a breath.",
        "We're going to give {n} a moment to come back.",
        "It seems {n} isn't with us right now. We'll wait just a bit.",
        "I'll put things on hold while we wait for {n}.",
        "One moment, everyone. It looks like {n} has stepped away briefly.",
        "Let's give {n} just a moment to return.",
        "We'll hold here for {n}. Thanks for your patience, everyone.",
        "Taking a brief pause while {n} is away.",
        "I noticed {n} has stepped out. We'll continue very shortly.",
        "Let's pause here and give {n} a moment to come back to us.",
        "Don't go anywhere — we're just waiting on {n} to rejoin.",
        "I'll keep things paused for {n}. Thanks for your patience.",
        "Giving {n} just a moment to get settled back in.",
        "We'll hold on here for {n}. It won't be long.",
        "A brief pause while we wait for {n} to return.",
        "Everyone sit tight — we're waiting for {n} to come back.",
    ],

    # ------------------------------------------------------------------ #
    # check_10s — light, casual, just a gentle ping                       #
    # ------------------------------------------------------------------ #
    "check_10s": [
        "{n}, are you there?",
        "Just checking in, {n} — everything okay?",
        "{n}, still with us?",
        "Hey {n}, we're waiting on you.",
        "Just a quick check — {n}, are you around?",
        "{n}? We're holding for you.",
        "Knock knock, {n}. You there?",
        "{n}, we haven't forgotten you.",
        "Just pinging you, {n} — come on back when you're ready.",
        "Everything alright, {n}?",
        "{n}, just letting you know we're still here.",
        "No pressure, {n}, just checking you're okay.",
        "Quick check, {n} — are you with us?",
        "{n}, we've got your seat saved.",
        "Just a gentle nudge, {n} — we're ready when you are.",
        "Hey there, {n}. We miss you already.",
        "{n}, just making sure you're good.",
        "Waving at you from over here, {n}.",
        "All good, {n}? We're still here.",
        "{n}, just popping in to say we're waiting.",
        "A little nudge for {n} — come find us when you can.",
        "We see your empty seat, {n}. Not judging, just saying.",
        "{n}, we'll be here when you get back.",
        "Just checking in, {n}. Take your time.",
        "Hey {n}, your lesson is patiently waiting for you.",
        "Nothing urgent, {n} — just letting you know we haven't moved on.",
        "Still holding on for you, {n}.",
        "{n}, no worries — just give us a wave when you're back.",
        "Just a friendly hello from the class, {n}.",
        "Your place is saved, {n}. Come back whenever you're ready.",
    ],

    # ------------------------------------------------------------------ #
    # check_30s — still warm but more noticeable, slightly humorous       #
    # ------------------------------------------------------------------ #
    "check_30s": [
        "{n}, we're still here — are you coming back soon?",
        "Half a minute in, {n}. I hope everything is okay.",
        "We haven't gone anywhere, {n}. Have you?",
        "{n}, the lesson is waiting patiently, like a very patient lesson.",
        "Thirty seconds, {n} — I'm starting to wonder if you found something more exciting.",
        "Everything alright, {n}? The class sends its warmest thoughts.",
        "{n}, if you left to get a snack, I hope it was worth it.",
        "Still waiting for you, {n}. No judgment — life happens.",
        "Did you go on a little adventure, {n}? We're all curious.",
        "{n}, we're holding the lesson for you. Take a deep breath and come back.",
        "I notice {n} is still away. Class, let's stay focused while we wait.",
        "Thirty seconds and counting, {n}. We miss your presence.",
        "{n}, I'm keeping your spot warm for you.",
        "Just making sure you're okay out there, {n}.",
        "{n}, come back soon — you're missing all the fun.",
        "I hope you're alright, {n}. We'll be here.",
        "Thirty seconds feels like forever in class time, {n}. Come on back.",
        "{n}, did the cat knock something over? We're patient either way.",
        "We're hanging on, {n}. No rush, but no forever either.",
        "Checking in again, {n}. Still here, still ready.",
        "{n}, I haven't moved the lesson without you — your loyalty is safe.",
        "We're at the thirty-second mark, {n}. Time is doing what time does.",
        "The class is curious about you, {n}. Come back and satisfy our curiosity.",
        "{n}, you've been gone long enough that I'm starting to narrate it.",
        "If you can hear me, {n}, give us a wave. Or a thumbs up. Or just appear.",
        "Still patiently waiting, {n}. Emphasis on patiently.",
        "Class, let's use this moment wisely. {n} will be back shortly.",
        "I believe in your swift return, {n}.",
        "{n}, your classmates are rooting for you.",
        "Come back to us, {n}. We're in the middle of something rather important.",
        "Just over thirty seconds, {n}. We trust you're on your way.",
        "If this were a movie, {n}, the dramatic music would be starting about now.",
        "Still here, {n}. Still waiting. Still friendly about it.",
        "We've only been waiting thirty seconds, {n}, but it feels like a much longer podcast intro.",
        "I know you didn't abandon us, {n}. You'll be back.",
    ],

    # ------------------------------------------------------------------ #
    # check_60s — playful urgency, gently ribbing, still kind             #
    # ------------------------------------------------------------------ #
    "check_60s": [
        "One full minute, {n}. I hope everything is alright out there.",
        "{n}, we are officially at the one-minute mark. Please do hurry.",
        "Sixty seconds, {n}. If you went for a snack, I hope it was delicious.",
        "The lesson and I are both here waiting for you, {n}.",
        "One minute down. {n}, wherever you are, we'd love to have you back.",
        "{n}, we can't hold the class indefinitely — please come back soon.",
        "Did you fall asleep, {n}? We've all been there. Wake up time.",
        "{n}, the rest of the class is very dedicated and also very curious about where you went.",
        "A minute is a long time in lesson years, {n}. Come back to us.",
        "I'm not worried, {n}. I'm just noting that it's been a minute. Literally.",
        "{n}, I want to think you've got a very good reason for this. I believe you.",
        "One minute in and still no {n}. Class, let's stay sharp.",
        "{n}, we need you. Well, we want you. We're fine, but come back.",
        "Sixty seconds of class time is not nothing, {n}. Let's get moving.",
        "I'm starting to wonder if {n} found a more interesting class. Rude.",
        "{n}, we are officially in the slightly-concerning zone. Please pop back in.",
        "You've been gone a full minute, {n}. I'm resisting the urge to send a search party.",
        "{n}, class waits for no one, but I'm making an exception because you're worth it.",
        "A minute of my finest waiting and still no {n}. I am patient but curious.",
        "Look, {n}, I don't want to be dramatic, but it has been one minute.",
        "The clock says one minute, {n}. What does your clock say?",
        "{n}, the lesson is starting to feel a little lopsided without you.",
        "I had this great moment planned for you, {n}. Please come back for it.",
        "One minute, {n}. I trust you. I do. But come back.",
        "Do hurry, {n}. We can't pause the universe forever, just the lesson.",
        "{n}, we've officially hit the sixty-second milestone. No trophy, just urgency.",
        "Still missing you, {n}. It's been a whole minute.",
        "{n}, whatever pulled you away, I hope it's sorted. We're ready for you.",
        "At the one-minute mark, {n}, I'm upgrading my gentle nudge to a firm one.",
        "Class, one minute in. Let's keep {n} in our thoughts and keep things moving as best we can.",
        "{n}, come on back — we really do need you here.",
        "Sixty seconds feels very long when we're waiting for someone specific, {n}.",
        "One minute, {n}. I'm not frowning. I'm just saying.",
        "The lesson misses you specifically, {n}. It said so. We all heard it.",
        "We're at one minute, {n}. I'm still friendly, but I am getting genuinely curious.",
    ],

    # ------------------------------------------------------------------ #
    # check_90s — firmer but warm, genuine concern mixed with mild        #
    #             impatience                                              #
    # ------------------------------------------------------------------ #
    "check_90s": [
        "{n}, it's been a minute and a half. I'm genuinely hoping you're alright.",
        "Ninety seconds, {n}. That's long enough that I want to check you're okay.",
        "I'm a little concerned now, {n}. Please let us know you're with us.",
        "{n}, we really need you back with us soon.",
        "A minute and a half is a significant absence, {n}. Come back to us.",
        "{n}, are you okay? The class and I are starting to worry.",
        "Ninety seconds in. {n}, I hope nothing is wrong.",
        "We've been holding on for you, {n}, but I do need you to come back very soon.",
        "{n}, if something came up, that's completely understandable. But please do return.",
        "I'm not going to sugarcoat it, {n}: ninety seconds is a long time in a lesson.",
        "{n}, the patience jar is getting a little lower. We'd love to see your face.",
        "Seriously now, {n}, is everything alright?",
        "{n}, I'm keeping a warm welcome ready for you, but please hurry.",
        "At ninety seconds, {n}, I have to ask — is there anything we need to know?",
        "We are well into the concerning-absence territory now, {n}. Please come back.",
        "{n}, I'm shifting from patient to mildly worried. That's a shift.",
        "One minute thirty. {n}, I'd really like to hear from you.",
        "{n}, the class is still here and we need you to be here too.",
        "Is everything okay, {n}? A minute and a half is quite a while.",
        "{n}, I'll keep things paused, but I do need you back with us before long.",
        "I'm taking a quiet breath and hoping you return soon, {n}.",
        "Ninety seconds, {n}. Whatever is happening out there, come back when you can.",
        "{n}, the rest of the class is being very understanding. Please honor that with a return.",
        "I hope this is just a connection issue, {n}, and not something more serious.",
        "{n}, I need you here. Not a suggestion — a genuine teacher request.",
        "We're at ninety seconds, {n}. I'm starting to weigh my options.",
        "Please come back, {n}. We're not going anywhere, but we need you.",
        "{n}, a minute and a half is enough for me to say: come back, right now, please.",
        "Something feels a little off without you here, {n}. Fix that.",
        "I'm going to keep the lesson on hold, {n}, but we do need you back very soon.",
    ],

    # ------------------------------------------------------------------ #
    # check_120s — clearly pressing, professional, a little exasperated-  #
    #              but-fond                                               #
    # ------------------------------------------------------------------ #
    "check_120s": [
        "Two minutes, {n}. I have to say, this is getting very long.",
        "{n}, we've been waiting two full minutes. This is now officially a long absence.",
        "It has been two minutes, {n}. Whatever is happening, please come back.",
        "{n}, two minutes is a lot to ask of a class. I need you here now.",
        "I'll be honest, {n}: two minutes is testing my legendary patience.",
        "{n}, come on. Two minutes. Please.",
        "The two-minute mark, {n}. I am still calm. I am definitely still calm.",
        "{n}, if you are within earshot of a screen, this is your call to action.",
        "Two minutes, everyone. {n}, wherever you are, now is the time to return.",
        "I've been patient, {n}, and I will remain patient, but please make it easier.",
        "{n}, this is officially a two-minute absence. That's a record I'd like to end now.",
        "Two minutes in, {n}. My warm feelings are still intact but they're doing some heavy lifting.",
        "{n}, the class is still here, still waiting, and still hoping for your return.",
        "I understand things happen, {n}, but two minutes is quite a while.",
        "{n}, I'm going to need you back in the next thirty seconds or so.",
        "Two minutes, {n}. I'm not disappointed. I'm not. But I'm not not-disappointed either.",
        "Come back, {n}. Right now would be an excellent time.",
        "{n}, two minutes have passed. This is my earnest, sincere, firm request that you return.",
        "I've now waited two minutes for you, {n}. No one can say I'm not committed.",
        "At the two-minute mark, {n}, I'm moving from patient to persistent.",
        "{n}, I love you as a student, which is exactly why I need you back here.",
        "Two minutes, {n}. I'm running out of polite ways to say please come back.",
        "{n}, this is your two-minute notice. Please return to class immediately.",
        "I am still here, {n}. I am still waiting. Please come back.",
        "The whole class has been remarkably patient, {n}. Honor that. Return.",
        "{n}, two minutes in, no sign of you. Let's fix that.",
        "You know what, {n}, I believe in your imminent return. Please make me right.",
        "It's been two minutes, {n}. This is not a drill. Come back to class.",
        "Two minutes, {n}. I have officially moved into the mildly-exasperated zone.",
        "I'll keep the lesson paused, {n}, but this is my last polite reminder before action.",
    ],

    # ------------------------------------------------------------------ #
    # boot_group — decisive, professional, apologetic to the rest of the  #
    #              class                                                   #
    # ------------------------------------------------------------------ #
    "boot_group": [
        "I'm sorry everyone, but I need to remove {n} from today's session so we can continue.",
        "We've waited three minutes for {n}, and for the good of the class I'll need to let them go for now.",
        "Thank you for your patience. I'm going to remove {n} from the session so we can move forward.",
        "Class, I apologize for the interruption. {n} will be removed so we don't fall further behind.",
        "In the interest of everyone's time, I'll be removing {n} from today's session.",
        "It's been three minutes. I'm sorry, {n}, but I need to continue the lesson without you.",
        "After three minutes of waiting, I'll need to remove {n} from the session. We'll catch up later.",
        "Class, I appreciate your patience. We're going to continue without {n} for now.",
        "{n}, I hope everything is alright. I'll need to remove you from today's session so class can resume.",
        "For the sake of the group, I'll be removing {n} from this session. We can reconnect afterwards.",
        "I'm sorry, everyone. Three minutes is as long as we can wait. {n} will be removed now.",
        "It's time to continue. {n}, I'll send you a recap and we can reconnect. Class, let's move on.",
        "I've given {n} every opportunity to return, but I need to keep the class moving.",
        "With apologies to {n} and to all of you, I'll proceed without them now.",
        "After three minutes, I have no choice but to remove {n} and continue the lesson.",
        "Class, thank you for being so understanding. {n} will be removed so we can resume.",
        "{n}, I'll follow up with you after class. For now, I need to continue with the group.",
        "Three minutes of holding. For everyone else's benefit, I'll remove {n} now.",
        "I'm going to resume the lesson and follow up with {n} separately. Thank you all.",
        "With the class's time in mind, I'm removing {n} from today's session.",
    ],

    # ------------------------------------------------------------------ #
    # final_solo — endlessly patient, warm, zero pressure, solo context   #
    # ------------------------------------------------------------------ #
    "final_solo": [
        "{n}, I'll keep the lesson paused for as long as you need. Come back whenever you're ready.",
        "No rush at all, {n}. I'll be here when you return.",
        "Take all the time you need, {n}. I'm not going anywhere.",
        "{n}, the lesson will be here waiting for you.",
        "I'm saving your place, {n}. Come back when you can.",
        "Whenever you're ready, {n}, we'll pick right up from where we left off.",
        "{n}, there's no timer on this. Come back whenever it works for you.",
        "The lesson is on hold, {n}, and I am perfectly content to wait.",
        "I'll be right here, {n}. Take the time you need.",
        "{n}, I'm not going anywhere. Come back when you're ready.",
        "Life sometimes interrupts learning, {n}. Come back when you can.",
        "{n}, your lesson will wait. Take care of what you need to.",
        "No pressure at all, {n}. I'll keep everything ready for your return.",
        "{n}, I'm here, patient, and absolutely ready to continue when you are.",
        "Come back in your own time, {n}. There's no rush here.",
        "{n}, the material isn't going anywhere, and neither am I.",
        "Everything is paused and waiting, {n}. The moment you're back, we go.",
        "I'll be your very patient teacher and wait as long as it takes, {n}.",
        "{n}, take care of what you need to. Learning will still be here.",
        "No judgment, no timer, no worries, {n}. Come back when you can.",
    ],

    # ------------------------------------------------------------------ #
    # solo_cycle — 80+ unique repeating nudges for solo mode              #
    # ------------------------------------------------------------------ #
    "solo_cycle": [
        "Still here, {n}. Take your time.",
        "Whenever you're ready, {n}.",
        "No rush at all, {n}. I'll be here.",
        "{n}, the lesson is patiently waiting for you.",
        "I haven't gone anywhere, {n}.",
        "Come back whenever you're good and ready, {n}.",
        "I've saved your place, {n}.",
        "{n}, the universe is very large but this lesson will wait.",
        "Still holding on for you, {n}.",
        "Take all the time you need, {n}.",
        "{n}, I'm here. Come back when you can.",
        "Life happens. Come back to us when you're able, {n}.",
        "{n}, your learning is on pause, not cancelled.",
        "I have nowhere more important to be right now, {n}.",
        "{n}, whenever you step back in, we'll carry on like nothing happened.",
        "Holding the space for you, {n}.",
        "The material is going nowhere, {n}. And neither am I.",
        "Still patiently waiting, {n}.",
        "{n}, I hope whatever took you away is going well.",
        "I'm keeping the lesson warm for you, {n}.",
        "Come back at your own pace, {n}.",
        "{n}, I'm the most patient teacher in the world right now.",
        "No timer running, {n}. Just an open door.",
        "{n}, the screen is still on. The lesson is still ready.",
        "I believe in your return, {n}.",
        "We'll get back to the good stuff the moment you're here, {n}.",
        "{n}, I'm not peeking at my watch. There is no watch.",
        "If you can hear me, {n}, just know there's no pressure.",
        "Still here. Still ready. Still {n}'s biggest fan.",
        "{n}, come back and let's make this lesson count.",
        "The lesson will be as good as you left it, {n}.",
        "{n}, I'll be honest — I'm using this time to think of new ways to explain things.",
        "Waiting is underrated. I am embracing the pause, {n}.",
        "{n}, today I'm learning patience. We're all learning something.",
        "If this were a movie, {n}, you'd walk back in at just the right moment.",
        "I'm picturing you having a very productive minute out there, {n}.",
        "{n}, no rush. Curiosity keeps.",
        "Still holding your spot, {n}. Consider it reserved.",
        "{n}, whenever you show up, it'll feel like perfect timing.",
        "I've brewed a mental cup of tea while I wait for you, {n}.",
        "{n}, I remain steadfastly optimistic about your imminent return.",
        "The only thing better than this pause will be when you come back, {n}.",
        "{n}, I'm using this quiet moment to appreciate how dedicated you are — normally.",
        "Somewhere out there, {n} is about to walk back in. I can feel it.",
        "I've decided to interpret this absence as a very dramatic entrance build-up, {n}.",
        "{n}, I'm telling myself you went to get something to drink. It's a good story.",
        "Waiting, {n}. Warmly. Without complaint.",
        "I'm imagining you sprinting back to your desk right now, {n}.",
        "{n}, the door is always open. Figuratively and otherwise.",
        "This silence is very peaceful, {n}. You can break it anytime.",
        "{n}, I'm leaving the welcome mat out.",
        "Serenely waiting, {n}.",
        "{n}, your lesson is like a bookmark — right where you left it.",
        "The world keeps spinning, and I keep waiting, {n}.",
        "{n}, I trust you. Come back when you're ready.",
        "Patience is a virtue, {n}. I'm being very virtuous right now.",
        "{n}, the knowledge you're about to gain is worth coming back for. I promise.",
        "I'm practicing my best patient-teacher face, {n}. You'll see it when you return.",
        "{n}, I hope you're having a moment of calm out there.",
        "Come back, {n}. The lesson's best part is still ahead.",
        "{n}, I'm not counting the seconds. Well, I am, but I'm doing it very lovingly.",
        "Your absence, {n}, has given me time to admire how far you've come.",
        "{n}, I've got everything queued up for your return.",
        "Whatever you're doing, {n}, I hope it's going well.",
        "{n}, the lesson curriculum is giving you the world's most patient stare.",
        "I could wait all day, {n}. I'm not going to, but I could.",
        "{n}, I'm holding the thread. Come pick it back up when you're ready.",
        "Here when you need me, {n}. No drama. Just here.",
        "{n}, I haven't skipped ahead. Not even a little.",
        "Waiting for you with great affection, {n}.",
        "{n}, your fellow materials are ready and waiting.",
        "I'll be the same old Theodore when you return, {n}.",
        "The lesson appreciates your commitment to dramatic timing, {n}.",
        "{n}, come back. I've got genuinely good things ready for you.",
        "This extended pause is brought to you by {n}, who will return momentarily.",
        "Still here, {n}. As promised.",
        "{n}, I'm not going anywhere. That's a teacher guarantee.",
        "I believe, with great confidence, that {n} will be back very soon.",
        "{n}, take a breath, sort what you need to sort, and come find me.",
        "Still waiting with open arms, {n}.",
        "I've kept your lesson at the same temperature, {n}. It's still warm.",
    ],

    # ------------------------------------------------------------------ #
    # welcome_back — celebratory, warm, no judgment, quick to move on     #
    # ------------------------------------------------------------------ #
    "welcome_back": [
        "Welcome back, {n}! Let's pick right up from where we left off.",
        "{n} is back! Great to have you with us again.",
        "There you are, {n}! We missed you. Let's continue.",
        "Welcome back, {n}! No need to explain — let's dive right back in.",
        "{n}, you're back! Excellent timing. Let's keep going.",
        "Oh wonderful, {n} has returned! Welcome back. Let's carry on.",
        "Good to see you, {n}. We're glad you made it back.",
        "{n} is back in the room! Let's get right back to it.",
        "Welcome back, {n}! We saved your place.",
        "{n}, you're back — and just in time. Let's resume.",
        "Glad you're back with us, {n}. Let's not waste another second.",
        "And {n} returns! Welcome back. Now, where were we?",
        "{n}, you're here! Perfect. Let's continue right from where we paused.",
        "Welcome back, {n}. Everything is ready to go.",
        "{n} is with us again — excellent! Let's keep moving.",
        "Great to have you back, {n}. No catch-up needed — we're right where we left you.",
        "Ah, {n}! There you are. Let's go.",
        "Welcome back, {n}. I kept everything exactly as you left it.",
        "{n}, you made it! Let's pick things right back up.",
        "So glad you're back, {n}. The lesson missed you. Now let's continue!",
        "And we're back in business. Welcome, {n}!",
        "{n} returns, and so does the lesson. Let's go.",
        "Good to have you, {n}. Ready when you are.",
        "Welcome back, {n}! I knew you wouldn't keep us waiting forever.",
        "{n}, you're back! Brilliant. Let's finish what we started.",
        "The gang's all here again. Welcome back, {n}.",
        "Wonderful to see you, {n}. Let's not lose any more time.",
        "{n} is back! Right, let's continue.",
        "Welcome back, {n}. No questions asked — just glad you're here.",
        "There's {n}! We've got a lesson to finish. Let's go!",
    ],
}
