"""Locale-specific Bayon Buddy mascot catalog and resolver.

Each of the 27 platform languages maps to a culturally inspired mascot variant
(secular Bayon-inspired study buddy per docs/brand/branding.txt). SVG assets
live at /mascots/{locale}.svg (web) and are generated by
scripts/generate_locale_mascots.py.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional

from .languages import SUPPORTED_LANGUAGES

DEFAULT_MASCOT_LOCALE = "en"
DEFAULT_MASCOT_PATH = "/bayon-mark.webp"
MASCOT_ASSET_PREFIX = "/mascots"


@dataclass(frozen=True)
class MascotVariant:
    locale: str
    region: str
    cultural_theme: str
    skin_tone: str
    robe: str
    accent: str
    pattern: str
    headpiece: str


# Culturally inspired palettes + motifs (secular mascot; not religious iconography).
MASCOT_CATALOG: Dict[str, MascotVariant] = {
    "en": MascotVariant("en", "United States / Global English", "Welcoming educator", "#c68642", "#1e3a8a", "#fbbf24", "stars", "mortarboard"),
    "es": MascotVariant("es", "Spain / Latin America", "Warm maestro", "#bf6a3a", "#b91c1c", "#facc15", "tiles", "sombrero cord"),
    "fr": MascotVariant("fr", "France", "Curious flaneur scholar", "#d4a574", "#1d4ed8", "#ef4444", "fleur", "beret"),
    "de": MascotVariant("de", "Germany", "Precise craft learner", "#ddb892", "#111827", "#fbbf24", "geometric", "scholar cap"),
    "it": MascotVariant("it", "Italy", "Renaissance artisan", "#c68642", "#166534", "#dc2626", "mosaic", "laurel"),
    "pt": MascotVariant("pt", "Portugal / Brazil", "Coastal explorer", "#a97142", "#065f46", "#fbbf24", "waves", "explorer band"),
    "nl": MascotVariant("nl", "Netherlands", "Canal-side inventor", "#f1c27d", "#f97316", "#2563eb", "dutch cross", "sailor cap"),
    "pl": MascotVariant("pl", "Poland", "Resilient reader", "#e0ac69", "#dc2626", "#f8fafc", "folk embroidery", "flower crown"),
    "ru": MascotVariant("ru", "Russia", "Winter storyteller", "#c68642", "#7f1d1d", "#fbbf24", "khokhloma", "ushanka"),
    "uk": MascotVariant("uk", "Ukraine", "Sunflower learner", "#ddb892", "#2563eb", "#facc15", "vyshyvanka", "wreath"),
    "tr": MascotVariant("tr", "Turkey", "Bridge of cultures", "#bf6a3a", "#b91c1c", "#fbbf24", "iznik", "fez"),
    "ar": MascotVariant("ar", "Arab world", "Desert astronomer", "#8d5524", "#065f46", "#fbbf24", "arabesque", "keffiyeh"),
    "he": MascotVariant("he", "Israel", "Startup mentor", "#d4a574", "#2563eb", "#f8fafc", "pomegranate", "kippah"),
    "hi": MascotVariant("hi", "India", "Guru of many paths", "#a97142", "#ea580c", "#fbbf24", "rangoli", "turban"),
    "bn": MascotVariant("bn", "Bangladesh / Bengal", "River delta scholar", "#bf6a3a", "#166534", "#dc2626", "alpana", "sari fold"),
    "ur": MascotVariant("ur", "Pakistan", "Poetry circle guide", "#c68642", "#065f46", "#fbbf24", "truck art", "topi"),
    "fa": MascotVariant("fa", "Persia / Iran", "Garden philosopher", "#ddb892", "#7c3aed", "#059669", "persian tile", "turban"),
    "zh": MascotVariant("zh", "China", "Diligent scholar", "#f1c27d", "#dc2626", "#fbbf24", "cloud motif", "scholar hat"),
    "ja": MascotVariant("ja", "Japan", "Mindful craftsman", "#f1c27d", "#1e3a8a", "#dc2626", "seigaiha", "hachimaki"),
    "ko": MascotVariant("ko", "Korea", "Seowon student", "#f1c27d", "#2563eb", "#dc2626", "dancheong", "gat"),
    "vi": MascotVariant("vi", "Vietnam", "Lotus learner", "#ddb892", "#b91c1c", "#fbbf24", "dong ho", "non la"),
    "th": MascotVariant("th", "Thailand", "Temple school smile", "#ddb892", "#7c3aed", "#fbbf24", "thai pattern", "chada"),
    "id": MascotVariant("id", "Indonesia", "Archipelago guide", "#bf6a3a", "#b91c1c", "#fbbf24", "batik", "peci"),
    "sw": MascotVariant("sw", "East Africa", "Ubuntu mentor", "#8d5524", "#166534", "#dc2626", "kanga", "kofia"),
    "el": MascotVariant("el", "Greece", "Aegean philosopher", "#d4a574", "#2563eb", "#f8fafc", "meander", "laurel"),
    "cs": MascotVariant("cs", "Czechia", "Bohemian inventor", "#ddb892", "#dc2626", "#2563eb", "folk star", "student cap"),
    "km": MascotVariant("km", "Cambodia", "Salareen homeland smile", "#c68642", "#7f1d1d", "#fbbf24", "apsara motif", "sampot sash"),
}


def is_supported_mascot_locale(locale: str) -> bool:
    return locale in MASCOT_CATALOG


def normalize_mascot_locale(locale: str | None) -> str:
    if not locale:
        return DEFAULT_MASCOT_LOCALE
    base = locale.strip().lower().split("-")[0].split("_")[0]
    if base in MASCOT_CATALOG:
        return base
    if base in SUPPORTED_LANGUAGES:
        return base
    return DEFAULT_MASCOT_LOCALE


def mascot_asset_path(locale: str, *, ext: str = "svg") -> str:
    code = normalize_mascot_locale(locale)
    return f"{MASCOT_ASSET_PREFIX}/{code}.{ext}"


def resolve_mascot(
    locale: str | None,
    *,
    enabled: bool = True,
    preview_locale: str | None = None,
) -> Dict[str, str]:
    """Return web asset path + metadata for the requested locale."""
    if not enabled:
        return {
            "locale": DEFAULT_MASCOT_LOCALE,
            "path": DEFAULT_MASCOT_PATH,
            "variant": MASCOT_CATALOG[DEFAULT_MASCOT_LOCALE].__dict__,
            "localized": False,
        }
    code = normalize_mascot_locale(preview_locale or locale)
    variant = MASCOT_CATALOG.get(code, MASCOT_CATALOG[DEFAULT_MASCOT_LOCALE])
    return {
        "locale": code,
        "path": mascot_asset_path(code),
        "variant": {
            "locale": variant.locale,
            "region": variant.region,
            "cultural_theme": variant.cultural_theme,
            "skin_tone": variant.skin_tone,
            "robe": variant.robe,
            "accent": variant.accent,
            "pattern": variant.pattern,
            "headpiece": variant.headpiece,
        },
        "localized": True,
    }


def mascot_catalog_list() -> List[Dict]:
    return [
        {
            "locale": v.locale,
            "region": v.region,
            "cultural_theme": v.cultural_theme,
            "path": mascot_asset_path(v.locale),
        }
        for v in MASCOT_CATALOG.values()
    ]
