"""Locale-specific Bayon Buddy mascot catalog and resolver.

Each of the 27 platform languages maps to a photo-realistic stone-carving mascot
variant derived from the canonical Khmer (Cambodia) Bayon Buddy art. WebP assets
live at /mascots/{locale}.webp and are generated by
scripts/generate_locale_mascots.py from apps/web/public/bayon-mark.webp.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional

from .languages import SUPPORTED_LANGUAGES

DEFAULT_MASCOT_LOCALE = "en"
DEFAULT_MASCOT_PATH = "/bayon-mark.webp"
MASCOT_ASSET_PREFIX = "/mascots"
MASCOT_ASSET_EXT = "webp"


@dataclass(frozen=True)
class MascotVariant:
    locale: str
    region: str
    cultural_theme: str
    skin_tone: str
    robe: str
    accent: str
    pattern: str
    headpiece: str
    # Photo-realistic stone tint (applied to the Khmer master carving).
    stone_hue_shift: float = 0.0
    stone_sat_mult: float = 1.0
    stone_bright_mult: float = 1.0
    stone_warmth: float = 0.0


# Culturally inspired palettes + stone-tone shifts (secular mascot).
MASCOT_CATALOG: Dict[str, MascotVariant] = {
    "en": MascotVariant("en", "United States / Global English", "Welcoming educator", "#c68642", "#1e3a8a", "#fbbf24", "stars", "mortarboard", 4, 0.94, 1.06, 0.06),
    "es": MascotVariant("es", "Spain / Latin America", "Warm maestro", "#bf6a3a", "#b91c1c", "#facc15", "tiles", "sombrero cord", 12, 1.06, 0.98, 0.14),
    "fr": MascotVariant("fr", "France", "Curious flaneur scholar", "#d4a574", "#1d4ed8", "#ef4444", "fleur", "beret", -6, 0.90, 1.08, -0.04),
    "de": MascotVariant("de", "Germany", "Precise craft learner", "#ddb892", "#111827", "#fbbf24", "geometric", "scholar cap", -10, 0.84, 0.94, -0.14),
    "it": MascotVariant("it", "Italy", "Renaissance artisan", "#c68642", "#166534", "#dc2626", "mosaic", "laurel", 8, 1.02, 1.02, 0.10),
    "pt": MascotVariant("pt", "Portugal / Brazil", "Coastal explorer", "#a97142", "#065f46", "#fbbf24", "waves", "explorer band", 6, 1.04, 0.96, 0.08),
    "nl": MascotVariant("nl", "Netherlands", "Canal-side inventor", "#f1c27d", "#f97316", "#2563eb", "dutch cross", "sailor cap", -4, 0.92, 1.04, -0.06),
    "pl": MascotVariant("pl", "Poland", "Resilient reader", "#e0ac69", "#dc2626", "#f8fafc", "folk embroidery", "flower crown", 2, 0.98, 1.00, 0.04),
    "ru": MascotVariant("ru", "Russia", "Winter storyteller", "#c68642", "#7f1d1d", "#fbbf24", "khokhloma", "ushanka", -14, 0.82, 0.90, -0.18),
    "uk": MascotVariant("uk", "Ukraine", "Sunflower learner", "#ddb892", "#2563eb", "#facc15", "vyshyvanka", "wreath", 10, 1.05, 1.04, 0.12),
    "tr": MascotVariant("tr", "Turkey", "Bridge of cultures", "#bf6a3a", "#b91c1c", "#fbbf24", "iznik", "fez", 14, 1.04, 0.97, 0.11),
    "ar": MascotVariant("ar", "Arab world", "Desert astronomer", "#8d5524", "#065f46", "#fbbf24", "arabesque", "keffiyeh", 18, 1.02, 0.95, 0.16),
    "he": MascotVariant("he", "Israel", "Startup mentor", "#d4a574", "#2563eb", "#f8fafc", "pomegranate", "kippah", -2, 0.96, 1.06, 0.02),
    "hi": MascotVariant("hi", "India", "Guru of many paths", "#a97142", "#ea580c", "#fbbf24", "rangoli", "turban", 16, 1.08, 0.96, 0.15),
    "bn": MascotVariant("bn", "Bangladesh / Bengal", "River delta scholar", "#bf6a3a", "#166534", "#dc2626", "alpana", "sari fold", 8, 1.06, 0.98, 0.12),
    "ur": MascotVariant("ur", "Pakistan", "Poetry circle guide", "#c68642", "#065f46", "#fbbf24", "truck art", "topi", 12, 1.04, 0.97, 0.13),
    "fa": MascotVariant("fa", "Persia / Iran", "Garden philosopher", "#ddb892", "#7c3aed", "#059669", "persian tile", "turban", 20, 1.06, 0.98, 0.14),
    "zh": MascotVariant("zh", "China", "Diligent scholar", "#f1c27d", "#dc2626", "#fbbf24", "cloud motif", "scholar hat", -8, 0.90, 1.02, -0.08),
    "ja": MascotVariant("ja", "Japan", "Mindful craftsman", "#f1c27d", "#1e3a8a", "#dc2626", "seigaiha", "hachimaki", -12, 0.88, 1.06, -0.10),
    "ko": MascotVariant("ko", "Korea", "Seowon student", "#f1c27d", "#2563eb", "#dc2626", "dancheong", "gat", -6, 0.92, 1.04, -0.06),
    "vi": MascotVariant("vi", "Vietnam", "Lotus learner", "#ddb892", "#b91c1c", "#fbbf24", "dong ho", "non la", 6, 1.02, 0.98, 0.08),
    "th": MascotVariant("th", "Thailand", "Temple school smile", "#ddb892", "#7c3aed", "#fbbf24", "thai pattern", "chada", 10, 1.04, 1.00, 0.10),
    "id": MascotVariant("id", "Indonesia", "Archipelago guide", "#bf6a3a", "#b91c1c", "#fbbf24", "batik", "peci", 14, 1.05, 0.96, 0.12),
    "sw": MascotVariant("sw", "East Africa", "Ubuntu mentor", "#8d5524", "#166534", "#dc2626", "kanga", "kofia", 22, 1.08, 0.92, 0.18),
    "el": MascotVariant("el", "Greece", "Aegean philosopher", "#d4a574", "#2563eb", "#f8fafc", "meander", "laurel", -4, 0.94, 1.06, -0.02),
    "cs": MascotVariant("cs", "Czechia", "Bohemian inventor", "#ddb892", "#dc2626", "#2563eb", "folk star", "student cap", -8, 0.90, 1.00, -0.08),
    "km": MascotVariant("km", "Cambodia", "Salareen homeland smile", "#c68642", "#7f1d1d", "#fbbf24", "apsara motif", "sampot sash", 0, 1.0, 1.0, 0.05),
}


def is_supported_mascot_locale(locale: str) -> bool:
    return locale in MASCOT_CATALOG


def normalize_mascot_locale(locale: str | None) -> str:
    if not locale:
        return DEFAULT_MASCOT_LOCALE
    base = locale.strip().lower().split("-")[0].split("_")[0]
    if base in MASCOT_CATALOG:
        return base
    if base in SUPPORTED_LANGUAGES:
        return base
    return DEFAULT_MASCOT_LOCALE


def mascot_asset_path(locale: str, *, ext: str = MASCOT_ASSET_EXT) -> str:
    code = normalize_mascot_locale(locale)
    return f"{MASCOT_ASSET_PREFIX}/{code}.{ext}"


def resolve_mascot(
    locale: str | None,
    *,
    enabled: bool = True,
    preview_locale: str | None = None,
) -> Dict[str, str]:
    """Return web asset path + metadata for the requested locale."""
    if not enabled:
        return {
            "locale": DEFAULT_MASCOT_LOCALE,
            "path": DEFAULT_MASCOT_PATH,
            "variant": MASCOT_CATALOG[DEFAULT_MASCOT_LOCALE].__dict__,
            "localized": False,
        }
    code = normalize_mascot_locale(preview_locale or locale)
    variant = MASCOT_CATALOG.get(code, MASCOT_CATALOG[DEFAULT_MASCOT_LOCALE])
    return {
        "locale": code,
        "path": mascot_asset_path(code),
        "variant": {
            "locale": variant.locale,
            "region": variant.region,
            "cultural_theme": variant.cultural_theme,
            "skin_tone": variant.skin_tone,
            "robe": variant.robe,
            "accent": variant.accent,
            "pattern": variant.pattern,
            "headpiece": variant.headpiece,
        },
        "localized": True,
    }


def mascot_catalog_list() -> List[Dict]:
    return [
        {
            "locale": v.locale,
            "region": v.region,
            "cultural_theme": v.cultural_theme,
            "path": mascot_asset_path(v.locale),
        }
        for v in MASCOT_CATALOG.values()
    ]
