// Auto-generated by scripts/generate_locale_mascots.py — do not edit.
export const MASCOT_SVG: Record<string, string> = {
  "ar": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Arab world">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#065f46"/>
      <stop offset="100%" stop-color="#fbbf24"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#fbbf24" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">arabesque</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#8d5524"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#8d5524" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#fbbf24" font-family="sans-serif">keffiyeh</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#065f46" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">AR</text>
</svg>
`,
  "bn": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Bangladesh / Bengal">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#166534"/>
      <stop offset="100%" stop-color="#dc2626"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#dc2626" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">alpana</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#bf6a3a"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#bf6a3a" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#dc2626" font-family="sans-serif">sari fold</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#166534" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">BN</text>
</svg>
`,
  "cs": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Czechia">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#dc2626"/>
      <stop offset="100%" stop-color="#2563eb"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#2563eb" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">folk star</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#ddb892"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#ddb892" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#2563eb" font-family="sans-serif">student cap</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#dc2626" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">CS</text>
</svg>
`,
  "de": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Germany">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#111827"/>
      <stop offset="100%" stop-color="#fbbf24"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#fbbf24" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">geometric</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#ddb892"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#ddb892" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#fbbf24" font-family="sans-serif">scholar cap</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#111827" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">DE</text>
</svg>
`,
  "el": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Greece">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#2563eb"/>
      <stop offset="100%" stop-color="#f8fafc"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#f8fafc" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">meander</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#d4a574"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#d4a574" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#f8fafc" font-family="sans-serif">laurel</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#2563eb" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">EL</text>
</svg>
`,
  "en": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — United States / Global English">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#1e3a8a"/>
      <stop offset="100%" stop-color="#fbbf24"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#fbbf24" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">stars</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#c68642"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#c68642" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#fbbf24" font-family="sans-serif">mortarboard</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#1e3a8a" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">EN</text>
</svg>
`,
  "es": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Spain / Latin America">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#b91c1c"/>
      <stop offset="100%" stop-color="#facc15"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#facc15" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">tiles</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#bf6a3a"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#bf6a3a" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#facc15" font-family="sans-serif">sombrero cord</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#b91c1c" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">ES</text>
</svg>
`,
  "fa": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Persia / Iran">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#7c3aed"/>
      <stop offset="100%" stop-color="#059669"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#059669" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">persian tile</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#ddb892"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#ddb892" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#059669" font-family="sans-serif">turban</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#7c3aed" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">FA</text>
</svg>
`,
  "fr": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — France">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#1d4ed8"/>
      <stop offset="100%" stop-color="#ef4444"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#ef4444" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">fleur</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#d4a574"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#d4a574" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#ef4444" font-family="sans-serif">beret</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#1d4ed8" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">FR</text>
</svg>
`,
  "he": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Israel">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#2563eb"/>
      <stop offset="100%" stop-color="#f8fafc"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#f8fafc" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">pomegranate</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#d4a574"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#d4a574" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#f8fafc" font-family="sans-serif">kippah</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#2563eb" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">HE</text>
</svg>
`,
  "hi": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — India">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#ea580c"/>
      <stop offset="100%" stop-color="#fbbf24"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#fbbf24" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">rangoli</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#a97142"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#a97142" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#fbbf24" font-family="sans-serif">turban</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#ea580c" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">HI</text>
</svg>
`,
  "id": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Indonesia">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#b91c1c"/>
      <stop offset="100%" stop-color="#fbbf24"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#fbbf24" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">batik</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#bf6a3a"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#bf6a3a" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#fbbf24" font-family="sans-serif">peci</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#b91c1c" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">ID</text>
</svg>
`,
  "it": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Italy">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#166534"/>
      <stop offset="100%" stop-color="#dc2626"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#dc2626" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">mosaic</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#c68642"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#c68642" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#dc2626" font-family="sans-serif">laurel</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#166534" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">IT</text>
</svg>
`,
  "ja": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Japan">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#1e3a8a"/>
      <stop offset="100%" stop-color="#dc2626"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#dc2626" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">seigaiha</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#f1c27d"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#f1c27d" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#dc2626" font-family="sans-serif">hachimaki</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#1e3a8a" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">JA</text>
</svg>
`,
  "km": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Cambodia">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#7f1d1d"/>
      <stop offset="100%" stop-color="#fbbf24"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#fbbf24" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">apsara motif</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#c68642"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#c68642" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#fbbf24" font-family="sans-serif">sampot sash</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#7f1d1d" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">KM</text>
</svg>
`,
  "ko": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Korea">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#2563eb"/>
      <stop offset="100%" stop-color="#dc2626"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#dc2626" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">dancheong</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#f1c27d"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#f1c27d" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#dc2626" font-family="sans-serif">gat</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#2563eb" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">KO</text>
</svg>
`,
  "nl": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Netherlands">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#f97316"/>
      <stop offset="100%" stop-color="#2563eb"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#2563eb" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">dutch cross</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#f1c27d"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#f1c27d" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#2563eb" font-family="sans-serif">sailor cap</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#f97316" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">NL</text>
</svg>
`,
  "pl": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Poland">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#dc2626"/>
      <stop offset="100%" stop-color="#f8fafc"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#f8fafc" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">folk embroidery</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#e0ac69"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#e0ac69" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#f8fafc" font-family="sans-serif">flower crown</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#dc2626" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">PL</text>
</svg>
`,
  "pt": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Portugal / Brazil">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#065f46"/>
      <stop offset="100%" stop-color="#fbbf24"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#fbbf24" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">waves</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#a97142"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#a97142" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#fbbf24" font-family="sans-serif">explorer band</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#065f46" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">PT</text>
</svg>
`,
  "ru": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Russia">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#7f1d1d"/>
      <stop offset="100%" stop-color="#fbbf24"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#fbbf24" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">khokhloma</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#c68642"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#c68642" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#fbbf24" font-family="sans-serif">ushanka</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#7f1d1d" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">RU</text>
</svg>
`,
  "sw": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — East Africa">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#166534"/>
      <stop offset="100%" stop-color="#dc2626"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#dc2626" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">kanga</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#8d5524"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#8d5524" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#dc2626" font-family="sans-serif">kofia</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#166534" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">SW</text>
</svg>
`,
  "th": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Thailand">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#7c3aed"/>
      <stop offset="100%" stop-color="#fbbf24"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#fbbf24" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">thai pattern</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#ddb892"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#ddb892" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#fbbf24" font-family="sans-serif">chada</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#7c3aed" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">TH</text>
</svg>
`,
  "tr": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Turkey">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#b91c1c"/>
      <stop offset="100%" stop-color="#fbbf24"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#fbbf24" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">iznik</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#bf6a3a"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#bf6a3a" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#fbbf24" font-family="sans-serif">fez</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#b91c1c" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">TR</text>
</svg>
`,
  "uk": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Ukraine">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#2563eb"/>
      <stop offset="100%" stop-color="#facc15"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#facc15" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">vyshyvanka</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#ddb892"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#ddb892" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#facc15" font-family="sans-serif">wreath</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#2563eb" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">UK</text>
</svg>
`,
  "ur": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Pakistan">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#065f46"/>
      <stop offset="100%" stop-color="#fbbf24"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#fbbf24" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">truck art</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#c68642"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#c68642" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#fbbf24" font-family="sans-serif">topi</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#065f46" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">UR</text>
</svg>
`,
  "vi": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — Vietnam">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#b91c1c"/>
      <stop offset="100%" stop-color="#fbbf24"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#fbbf24" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">dong ho</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#ddb892"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#ddb892" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#fbbf24" font-family="sans-serif">non la</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#b91c1c" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">VI</text>
</svg>
`,
  "zh": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 360" role="img" aria-label="Salareen Bayon Buddy — China">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0b1020" stop-opacity="0"/>
      <stop offset="100%" stop-color="#0b1020" stop-opacity="0.15"/>
    </linearGradient>
    <linearGradient id="robe" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#dc2626"/>
      <stop offset="100%" stop-color="#fbbf24"/>
    </linearGradient>
  </defs>
  <rect width="200" height="360" fill="url(#bg)"/>
  <!-- Bodhi leaf -->
  <path d="M148 250 C170 220 185 195 175 170 C165 150 140 155 128 175 C116 195 125 230 148 250 Z" fill="#16a34a" opacity="0.9"/>
  <path d="M128 175 C135 190 140 210 148 250" fill="none" stroke="#065f46" stroke-width="2"/>
  <!-- S-curve body / robe -->
  <path d="M72 150 C55 190 58 240 78 280 C95 312 118 328 128 340 C138 328 158 310 170 270 C182 230 175 190 158 150 Z" fill="url(#robe)"/>
  <!-- Cultural band -->
  <rect x="68" y="248" width="120" height="18" rx="6" fill="#fbbf24" opacity="0.85"/>
  <text x="128" y="261" text-anchor="middle" font-size="8" fill="#fff" font-family="sans-serif">cloud motif</text>
  <!-- Face (Bayon serene smile) -->
  <ellipse cx="128" cy="108" rx="58" ry="62" fill="#f1c27d"/>
  <ellipse cx="128" cy="112" rx="52" ry="54" fill="#f1c27d" opacity="0.95"/>
  <!-- Closed serene eyes -->
  <path d="M96 104 Q108 98 120 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <path d="M136 104 Q148 98 160 104" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Gentle smile -->
  <path d="M108 128 Q128 138 148 128" fill="none" stroke="#5c3d2e" stroke-width="3" stroke-linecap="round"/>
  <!-- Headpiece hint -->
  <text x="128" y="58" text-anchor="middle" font-size="9" fill="#fbbf24" font-family="sans-serif">scholar hat</text>
  <!-- Gold S medallion -->
  <circle cx="128" cy="210" r="22" fill="#fbbf24" stroke="#b45309" stroke-width="2"/>
  <text x="128" y="217" text-anchor="middle" font-size="22" font-weight="700" fill="#78350f" font-family="Georgia, serif">S</text>
  <!-- Locale badge -->
  <rect x="8" y="8" width="44" height="20" rx="6" fill="#dc2626" opacity="0.9"/>
  <text x="30" y="22" text-anchor="middle" font-size="11" fill="#fff" font-family="sans-serif">ZH</text>
</svg>
`,
};
