"""Full-line Simplified Chinese and Khmer translations for featured songs."""

from __future__ import annotations


CURATED_ZH_KM: dict[str, dict[str, str]] = {
    "i go to work": {"zh": "我去上班", "km": "ខ្ញុំទៅធ្វើការ"},
    "i go to school": {"zh": "我去上学", "km": "ខ្ញុំទៅសាលារៀន"},
    "i say hello": {"zh": "我说你好", "km": "ខ្ញុំនិយាយថា សួស្តី"},
    "i learn new rules": {"zh": "我学习新规则", "km": "ខ្ញុំរៀនច្បាប់ថ្មីៗ"},
    "at the bank": {"zh": "在银行", "km": "នៅធនាគារ"},
    "i count my cash": {"zh": "我数我的现金", "km": "ខ្ញុំរាប់លុយរបស់ខ្ញុំ"},
    "at the office": {"zh": "在办公室", "km": "នៅការិយាល័យ"},
    "i make a plan": {"zh": "我制订计划", "km": "ខ្ញុំរៀបចំផែនការ"},
    "walk to the store": {"zh": "走路去商店", "km": "ដើរទៅហាង"},
    "walk to the bus": {"zh": "走路去公交车站", "km": "ដើរទៅឡានក្រុង"},
    "pack my bag": {"zh": "收拾我的包", "km": "រៀបចំកាបូបរបស់ខ្ញុំ"},
    "come with us": {"zh": "跟我们来", "km": "មកជាមួយពួកយើង"},
    "bank bank bank": {"zh": "银行，银行，银行", "km": "ធនាគារ ធនាគារ ធនាគារ"},
    "supermarket": {"zh": "超市", "km": "ផ្សារទំនើប"},
    "restaurant restaurant": {"zh": "餐厅，餐厅", "km": "ភោជនីយដ្ឋាន ភោជនីយដ្ឋាន"},
    "i can say it": {"zh": "我会说", "km": "ខ្ញុំអាចនិយាយវាបាន"},
    "food food food": {"zh": "食物，食物，食物", "km": "អាហារ អាហារ អាហារ"},
    "please and thank you": {"zh": "请和谢谢", "km": "សូម និង អរគុណ"},
    "travel words": {"zh": "旅行用语", "km": "ពាក្យសម្រាប់ការធ្វើដំណើរ"},
    "i know them too": {"zh": "我也知道这些词", "km": "ខ្ញុំក៏ស្គាល់ពាក្យទាំងនេះដែរ"},
    "i need a ticket": {"zh": "我需要一张票", "km": "ខ្ញុំត្រូវការសំបុត្រមួយ"},
    "i need a map": {"zh": "我需要一张地图", "km": "ខ្ញុំត្រូវការផែនទីមួយ"},
    "i find the way": {"zh": "我找到路了", "km": "ខ្ញុំរកផ្លូវឃើញ"},
    "and then i clap": {"zh": "然后我拍手", "km": "ហើយបន្ទាប់មកខ្ញុំទះដៃ"},
    "at the airport": {"zh": "在机场", "km": "នៅអាកាសយានដ្ឋាន"},
    "i wait in line": {"zh": "我排队等候", "km": "ខ្ញុំឈររង់ចាំជាជួរ"},
    "at the hotel": {"zh": "在酒店", "km": "នៅសណ្ឋាគារ"},
    "i feel just fine": {"zh": "我感觉很好", "km": "ខ្ញុំមានអារម្មណ៍ល្អ"},
    "one sandwich please": {"zh": "请给我一个三明治", "km": "សូមនំសាំងវិចមួយ"},
    "one cup of tea": {"zh": "一杯茶", "km": "តែមួយពែង"},
    "how much is this": {"zh": "这个多少钱？", "km": "នេះថ្លៃប៉ុន្មាន?"},
    "can you help me": {"zh": "你能帮我吗？", "km": "តើអ្នកអាចជួយខ្ញុំបានទេ?"},
    "hello friend how are you": {"zh": "你好，朋友，你好吗？", "km": "សួស្តីមិត្ត តើអ្នកសុខសប្បាយទេ?"},
    "i am good yes me too": {"zh": "我很好，是的，我也是", "km": "ខ្ញុំសុខសប្បាយ បាទ ខ្ញុំក៏ដូចគ្នា"},
    "look a bus a car a train": {"zh": "看，一辆公交车、一辆汽车和一列火车", "km": "មើល ឡានក្រុង ឡាន និងរថភ្លើង"},
    "see the sun see the rain": {"zh": "看太阳，看雨水", "km": "មើលព្រះអាទិត្យ មើលភ្លៀង"},
    "wheels on the bus go round and round": {
        "zh": "公交车的轮子转呀转",
        "km": "កង់ឡានក្រុងវិលជុំវិញ",
    },
    "all through the town": {"zh": "一路穿过整个城镇", "km": "ពេញមួយទីក្រុង"},
    "open shut the door goes": {"zh": "车门开了又关", "km": "ទ្វារបើក ហើយបិទ"},
    "everywhere it goes": {"zh": "它到处行驶", "km": "វាទៅគ្រប់ទីកន្លែង"},
    "where we going far away": {"zh": "我们去哪里？去很远的地方", "km": "តើយើងទៅណា? ទៅឆ្ងាយ"},
    "to the park to play": {"zh": "去公园玩", "km": "ទៅលេងនៅសួនច្បារ"},
    "hold my hand dont let go": {"zh": "牵着我的手，别放开", "km": "កាន់ដៃខ្ញុំ កុំលែង"},
    "fast and fast and slow": {"zh": "快一点，再快一点，然后慢下来", "km": "លឿន ហើយលឿន ហើយយឺត"},
    "up and down the people go": {"zh": "人们上上下下", "km": "មនុស្សឡើង ហើយចុះ"},
    "waving hi waving low": {"zh": "挥手问好，上下挥手", "km": "គ្រវីដៃខ្ពស់ គ្រវីដៃទាប"},
    "beep beep says the horn": {"zh": "喇叭说：嘟嘟", "km": "ស៊ីប ស៊ីប សំឡេងស៊ីផ្លេ"},
    "since the early morn": {"zh": "从清晨开始", "km": "តាំងពីព្រឹកព្រលឹម"},
    "hello am i wrong": {"zh": "你好，我错了吗？", "km": "សួស្តី តើខ្ញុំខុសទេ?"},
    "morning singing my song": {"zh": "早晨唱着我的歌", "km": "ពេលព្រឹក ខ្ញុំច្រៀងបទរបស់ខ្ញុំ"},
    "the sun is shining": {"zh": "阳光灿烂", "km": "ព្រះអាទិត្យកំពុងរះ"},
    "we can all sing along": {"zh": "我们都可以一起唱", "km": "យើងទាំងអស់គ្នាអាចច្រៀងជាមួយគ្នា"},
    "up is where i look": {"zh": "我向上看", "km": "ខ្ញុំមើលទៅលើ"},
    "down is where i go": {"zh": "我向下走", "km": "ខ្ញុំទៅខាងក្រោម"},
    "left and right are friends": {"zh": "左边和右边是朋友", "km": "ឆ្វេង និងស្តាំជាមិត្តនឹងគ្នា"},
    "come and learn them slow": {"zh": "来慢慢学习它们", "km": "មករៀនពាក្យទាំងនេះយឺតៗ"},
    "words this way words this way": {"zh": "词语走这边，词语走这边", "km": "ពាក្យនៅខាងនេះ ពាក្យនៅខាងនេះ"},
    "say it soft say it loud": {"zh": "轻声说，再大声说", "km": "និយាយតិចៗ និយាយឮៗ"},
    "we can learn them now": {"zh": "我们现在就能学会", "km": "យើងអាចរៀនវាឥឡូវនេះ"},
    "left and right up and down": {"zh": "左和右，上和下", "km": "ឆ្វេង និងស្តាំ លើ និងក្រោម"},
    "round and round we go": {"zh": "我们一圈又一圈地转", "km": "យើងវិលជុំវិញ"},
    "one hand points to you": {"zh": "一只手指向你", "km": "ដៃមួយចង្អុលទៅអ្នក"},
    "two feet walk the floor": {"zh": "两只脚在地板上走", "km": "ជើងពីរដើរលើកម្រាល"},
    "turn around and smile": {"zh": "转过身来微笑", "km": "បង្វិលខ្លួន ហើយញញឹម"},
    "then we ask for more": {"zh": "然后我们想再学更多", "km": "បន្ទាប់មកយើងសុំបន្ថែមទៀត"},
    "this way that way": {"zh": "这边，那边", "km": "ខាងនេះ ខាងនោះ"},
    "near and far": {"zh": "近和远", "km": "ជិត និងឆ្ងាយ"},
    "every word can take us": {"zh": "每个词都能带我们前行", "km": "ពាក្យនីមួយៗអាចនាំយើងទៅបាន"},
    "where we are": {"zh": "到我们所在的地方", "km": "ទៅកន្លែងដែលយើងនៅ"},
}
