apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aoep
resources:
  - namespace.yaml
  - configmap.yaml
  - services.yaml
  - autoscaling.yaml
  - redis.yaml
  - ingress.yaml
  - ingress-origin.yaml
  - llm-vllm.yaml
  - harvester.yaml
  - retention-cronjob.yaml
