#!/usr/bin/env python3
"""Generate photo-realistic locale Bayon Buddy WebP mascots (27 languages).

Each locale has its own transparent *base* carving at
apps/web/public/mascots/base/{locale}.webp — same serene face, Khmer lotus crown,
and S-with-bodhi-leaf medallion, but a slightly different physique (build) and
arm/leg placement (pose). The bases are produced by scripts/build_mascot_bases.py
from reference-guided art. This step layers each locale's deterministic stone
color tint (hue / saturation / brightness / warmth from MASCOT_CATALOG) on top of
its base, so every language differs in BOTH geometry and colour.

The Khmer (km) base is the canonical master (apps/web/public/bayon-mark.webp),
copied unchanged. If a locale base is missing, the master is used as a fallback.
"""

from __future__ import annotations

import colorsys
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "packages" / "shared" / "src"))

from aoep_shared.mascots import MASCOT_CATALOG, MascotVariant  # noqa: E402

MASTER = ROOT / "apps" / "web" / "public" / "bayon-mark.webp"
WEB_OUT = ROOT / "apps" / "web" / "public" / "mascots"
BASE_DIR = WEB_OUT / "base"
MOBILE_OUT = ROOT / "apps" / "mobile" / "assets" / "mascots"
MOBILE_TS = ROOT / "apps" / "mobile" / "src" / "mascots" / "imageAssets.ts"


def _base_path(locale: str) -> Path:
    """Per-locale base carving, falling back to the canonical master."""
    p = BASE_DIR / f"{locale}.webp"
    return p if p.is_file() else MASTER


def _apply_stone_tint(img, variant: MascotVariant):
    from PIL import Image

    rgba = img.convert("RGBA")
    pixels = rgba.load()
    hs = variant.stone_hue_shift / 360.0
    sat_m = variant.stone_sat_mult
    bright_m = variant.stone_bright_mult
    warmth = variant.stone_warmth
    w, h = rgba.size
    for y in range(h):
        for x in range(w):
            r, g, b, a = pixels[x, y]
            if a < 8:
                continue
            rf, gf, bf = r / 255.0, g / 255.0, b / 255.0
            hue, sat, val = colorsys.rgb_to_hsv(rf, gf, bf)
            hue = (hue + hs) % 1.0
            sat = max(0.0, min(1.0, sat * sat_m))
            val = max(0.0, min(1.0, val * bright_m))
            rf, gf, bf = colorsys.hsv_to_rgb(hue, sat, val)
            r, g, b = int(rf * 255), int(gf * 255), int(bf * 255)
            if warmth > 0:
                r = min(255, int(r + warmth * 30))
                b = max(0, int(b - warmth * 20))
            elif warmth < 0:
                b = min(255, int(b - warmth * 24))
                r = max(0, int(r + warmth * 14))
            pixels[x, y] = (r, g, b, a)
    return rgba


def main() -> None:
    if not MASTER.is_file():
        raise SystemExit(f"missing master mascot: {MASTER}")

    from PIL import Image

    WEB_OUT.mkdir(parents=True, exist_ok=True)
    MOBILE_OUT.mkdir(parents=True, exist_ok=True)
    MOBILE_TS.parent.mkdir(parents=True, exist_ok=True)

    entries: list[str] = []

    for old in WEB_OUT.glob("*.svg"):
        old.unlink()

    for locale, variant in sorted(MASCOT_CATALOG.items()):
        web_path = WEB_OUT / f"{locale}.webp"
        mobile_path = MOBILE_OUT / f"{locale}.webp"
        if variant.locale == "km":
            # Canonical homeland carving: master geometry, copied unchanged.
            shutil.copy2(MASTER, web_path)
        else:
            base = Image.open(_base_path(locale))
            out = _apply_stone_tint(base, variant)
            out.save(web_path, format="WEBP", quality=92, method=6)
        shutil.copy2(web_path, mobile_path)
        entries.append(f'  {locale}: require("../../assets/mascots/{locale}.webp"),')

    MOBILE_TS.write_text(
        "// Auto-generated by scripts/generate_locale_mascots.py — do not edit.\n"
        "export const MASCOT_IMAGES: Record<string, number> = {\n"
        + "\n".join(entries)
        + "\n};\n",
        encoding="utf-8",
    )
    print(f"Generated {len(MASCOT_CATALOG)} photo-realistic locale mascots -> {WEB_OUT}")


if __name__ == "__main__":
    main()
