"""Scenario-based training agents for critical thinking and emergency drills."""

from .agents import (
    CriticalThinkingCoachAgent,
    EmergencyScenarioCoachAgent,
    ForesightPrepAgent,
    LearningBehaviorCoachAgent,
    QuickDecisionAgent,
    SituationalAnalysisAgent,
)
from .catalog import (
    catalog_capacity,
    catalog_meta,
    count_scenarios,
    count_scenarios_for_track,
    generate_scenario,
    get_scenario,
    knowledge_overview,
    knowledge_source_list,
    list_domains,
    list_families_meta,
    list_scenarios,
    list_scenarios_for_track,
    random_procedural_scenario,
    random_scenario,
    reload_catalog,
    search_knowledge,
)
from .knowledge_base import (
    KNOWLEDGE,
    ReferenceFact,
    all_facts,
    attach_references,
    facts_for,
)
from .models import (
    AgentTurn,
    ScenarioDefinition,
    TrainingAgentRole,
    TrainingEvent,
    TrainingPhase,
    TrainingSessionState,
)
from .roster import PLATFORM_AGENTS, PlatformAgent, agent_roster_dict, list_agents
from .tracks import TRAINING_TRACKS, TrainingTrack, get_track, list_tracks, track_to_dict
from .session import TrainingSession, TrainingSessionStore

__all__ = [
    "AgentTurn",
    "all_facts",
    "attach_references",
    "catalog_capacity",
    "catalog_meta",
    "count_scenarios",
    "count_scenarios_for_track",
    "CriticalThinkingCoachAgent",
    "EmergencyScenarioCoachAgent",
    "facts_for",
    "ForesightPrepAgent",
    "generate_scenario",
    "get_scenario",
    "get_track",
    "KNOWLEDGE",
    "knowledge_overview",
    "knowledge_source_list",
    "LearningBehaviorCoachAgent",
    "list_domains",
    "list_families_meta",
    "list_scenarios",
    "list_scenarios_for_track",
    "list_tracks",
    "PLATFORM_AGENTS",
    "PlatformAgent",
    "QuickDecisionAgent",
    "random_procedural_scenario",
    "random_scenario",
    "ReferenceFact",
    "reload_catalog",
    "ScenarioDefinition",
    "search_knowledge",
    "SituationalAnalysisAgent",
    "TRAINING_TRACKS",
    "track_to_dict",
    "TrainingAgentRole",
    "TrainingEvent",
    "TrainingPhase",
    "TrainingSession",
    "TrainingSessionState",
    "TrainingSessionStore",
    "TrainingTrack",
    "agent_roster_dict",
    "list_agents",
]
