"""Storyboard scenes for CA DMV permit courses (basics, signs, sharing)."""

from __future__ import annotations

from .types import Cast, ObjectCallout, Scene, SegmentStoryboard

C = Cast
O = ObjectCallout


def _seg(
    lesson_id: str,
    idx: int,
    *,
    title: str,
    backdrop: str,
    camera: str,
    narration: str,
    cast: list[Cast],
    objects: list[ObjectCallout] | None = None,
    concept: str = "",
    verse: str = "",
    goal: str = "",
    scene_id: str = "",
) -> SegmentStoryboard:
    sid = scene_id or f"{lesson_id}-{idx:02d}"
    return SegmentStoryboard(
        lesson_id=lesson_id,
        slide_index=idx,
        verse_label=verse or title,
        learning_goal=goal or concept,
        scene=Scene(
            scene_id=sid,
            title=title,
            backdrop=backdrop,
            camera=camera,
            narration=narration,
            cast=tuple(cast),
            objects=tuple(objects or ()),
            concept=concept,
        ),
    )


def build_dmv_basics(lesson_id: str = "ca-dmv-permit-basics") -> list[SegmentStoryboard]:
    return [
        _seg(
            lesson_id, 0,
            title="Prep, not a DMV course",
            backdrop="residential",
            camera="ken-burns",
            concept="Practice aid — always verify the current CA Driver's Handbook.",
            narration="This lesson is study practice, not an official DMV course. Always check the current California Driver's Handbook.",
            cast=[C("car-red", 280, 340, motion="drive"), C("adult", 520, 300), C("teen", 580, 310, motion="sway")],
            objects=[O("Handbook is the authority", 40, 80)],
            goal="Treat this as practice; confirm rules in the official handbook.",
        ),
        _seg(
            lesson_id, 1,
            title="California learner's permit overview",
            backdrop="residential",
            camera="push-in",
            concept="Supervised practice only — licensed adult required.",
            narration="A provisional permit lets you practice with a licensed adult. You cannot drive alone or for hire.",
            cast=[C("car-blue", 300, 340, scale=1.1, motion="drive"), C("adult", 500, 300), C("teen", 560, 310)],
            objects=[O("Licensed adult required", 40, 80), O("No solo driving", 700, 100)],
            goal="Know what a provisional permit allows and forbids.",
        ),
        _seg(
            lesson_id, 2,
            title="Right-of-way at stops",
            backdrop="intersection",
            camera="ken-burns",
            concept="First to arrive goes first; yield to the right when tied.",
            narration="At a four-way stop, the first vehicle to arrive goes first. If two arrive together, yield to the driver on your right.",
            cast=[
                C("sign-stop", 160, 200, scale=0.9, motion="pulse"),
                C("car-red", 280, 360, motion="approach"),
                C("car-blue", 620, 280, scale=0.85, motion="cross-left", flip=True),
                C("pedestrian", 480, 400, motion="walk"),
            ],
            objects=[O("First in, first out", 40, 80)],
            goal="Apply four-way stop right-of-way correctly.",
        ),
        _seg(
            lesson_id, 3,
            title="California Basic Speed Law",
            backdrop="freeway",
            camera="pan-left",
            concept="Never drive faster than is safe — even under the posted limit.",
            narration="The posted limit is a maximum for ideal conditions. Slow down for weather, traffic, and visibility.",
            cast=[
                C("sign-speed", 120, 180, scale=0.9, motion="pulse"),
                C("car-green", 360, 340, motion="drive"),
                C("truck", 620, 310, scale=0.95, motion="drive"),
            ],
            objects=[O("Conditions first", 700, 90)],
            goal="Apply the Basic Speed Law in real conditions.",
        ),
        _seg(
            lesson_id, 4,
            title="Following distance",
            backdrop="freeway",
            camera="pan-right",
            concept="Keep at least a three-second gap; add more when conditions worsen.",
            narration="Use at least a three-second following gap in good conditions. Give yourself more space in rain, fog, or behind trucks.",
            cast=[
                C("car-red", 200, 340, motion="drive"),
                C("car-blue", 420, 350, scale=0.95, motion="drive"),
                C("truck", 680, 320, scale=0.9, motion="drive"),
            ],
            objects=[O("3-second rule", 40, 90)],
            goal="Maintain a safe space cushion.",
        ),
        _seg(
            lesson_id, 5,
            title="Signals and lane changes",
            backdrop="freeway",
            camera="dolly-shake",
            concept="Mirror, signal, shoulder-check, then move.",
            narration="Signal before turns and lane changes. Check mirrors, signal, check your blind spot over your shoulder, then move smoothly.",
            cast=[
                C("car-green", 400, 340, scale=1.1, motion="drive"),
                C("motorcycle", 260, 380, scale=0.85, motion="drive"),
                C("car-red", 700, 350, scale=0.9, motion="drive"),
            ],
            objects=[O("Shoulder check every time", 40, 90)],
            goal="Execute safe lane changes with a shoulder check.",
        ),
        _seg(
            lesson_id, 6,
            title="Turning and red lights in California",
            backdrop="intersection",
            camera="push-in",
            concept="Right on red after a full stop — unless a sign forbids it.",
            narration="California generally allows a right turn on red after a complete stop unless a sign prohibits it. Yield to pedestrians and cross traffic.",
            cast=[
                C("traffic-light-red", 500, 120, scale=1.0, motion="flash"),
                C("car-blue", 300, 360, motion="approach"),
                C("pedestrian", 520, 390, motion="cross-right"),
                C("sign-stop", 160, 200, scale=0.7),
            ],
            objects=[O("Full stop, then yield", 40, 80)],
            goal="Turn on red legally and safely.",
        ),
        _seg(
            lesson_id, 7,
            title="School buses in California",
            backdrop="school-zone",
            camera="zoom-punch",
            concept="Red lights and stop arm mean stop — both ways on undivided roads.",
            narration="When a school bus shows flashing red lights and a stop arm on an undivided road, traffic in both directions must stop.",
            cast=[
                C("school-bus", 380, 300, scale=1.1, motion="bob"),
                C("child", 560, 370, motion="hop"),
                C("car-blue", 160, 360, motion="approach"),
                C("sign-school", 720, 180, scale=0.8, motion="pulse"),
            ],
            objects=[O("Red lights = stop", 40, 90)],
            goal="Stop correctly for school buses.",
        ),
        _seg(
            lesson_id, 8,
            title="Seat belts and phones",
            backdrop="freeway",
            camera="dolly-shake",
            concept="Buckle every rider; no handheld phone while driving.",
            narration="California requires seat belts. Handheld phone use while driving is restricted — use hands-free or pull over safely.",
            cast=[
                C("car-red", 380, 340, scale=1.1, motion="drive"),
                C("phone-ban", 700, 200, scale=1.0, motion="pulse"),
                C("adult", 200, 300, motion="bob"),
                C("child", 260, 310, motion="sway"),
            ],
            objects=[O("Buckle up · phone down", 40, 90)],
            goal="Wear belts and avoid phone distractions.",
        ),
        _seg(
            lesson_id, 9,
            title="DUI limits in California",
            backdrop="night-road",
            camera="ken-burns",
            concept="0.08% BAC for adults 21+; zero tolerance under 21.",
            narration="For drivers 21 and older, the BAC limit is 0.08 percent. Drivers under 21 face zero-tolerance rules. Never drive impaired.",
            cast=[
                C("car-blue", 300, 340, motion="drive"),
                C("sign-warning", 650, 200, scale=0.85, motion="pulse"),
            ],
            objects=[O("Arrange another ride", 40, 80)],
            goal="Never drive impaired; know BAC limits.",
        ),
        _seg(
            lesson_id, 10,
            title="After a crash",
            backdrop="intersection",
            camera="static",
            concept="Stop, aid if safe, exchange info, report when required.",
            narration="If safe, move out of traffic and turn on hazards. Call 911 for injuries. Exchange names, contact, license, and insurance information.",
            cast=[
                C("car-red", 300, 340, motion="bob"),
                C("car-blue", 480, 350, scale=0.95, motion="sway"),
                C("adult", 400, 280, motion="bob"),
                C("ambulance", 700, 300, scale=0.85, motion="drive"),
            ],
            objects=[O("Exchange info · no fault debate", 40, 85)],
            goal="Handle a collision calmly and legally.",
        ),
        _seg(
            lesson_id, 11,
            title="Study next, then pause",
            backdrop="residential",
            camera="pull-out",
            concept="Short study blocks beat marathon cramming.",
            narration="Review signs and sharing the road next. Prefer 15 to 20 minute blocks with practice quizzes over multi-hour cramming.",
            cast=[
                C("car-green", 360, 340, scale=1.1, motion="drive"),
                C("teen", 560, 300, motion="bob"),
                C("adult", 620, 290, motion="sway"),
            ],
            objects=[O("Spaced practice wins", 40, 90)],
            goal="Plan the next short study block.",
        ),
    ]


def build_dmv_signs(lesson_id: str = "ca-dmv-permit-signs") -> list[SegmentStoryboard]:
    return [
        _seg(
            lesson_id, 0,
            title="Regulatory signs",
            backdrop="intersection",
            camera="ken-burns",
            concept="White rectangles set rules you must obey.",
            narration="Regulatory signs tell you what is required or forbidden — speed limits, one way, do not enter, and more.",
            cast=[
                C("sign-do-not-enter", 200, 180, motion="pulse"),
                C("sign-one-way", 400, 190, motion="bob"),
                C("sign-speed", 600, 185, motion="sway"),
                C("car-green", 400, 360, motion="drive"),
            ],
            objects=[O("Rules, not suggestions", 40, 90)],
        ),
        _seg(
            lesson_id, 1,
            title="Yield and stop",
            backdrop="intersection",
            camera="push-in",
            concept="Yield = give way; stop = full stop first.",
            narration="A red-and-white triangle is yield — slow and give way. A stop sign requires a complete stop behind the limit line.",
            cast=[
                C("sign-stop", 180, 190, scale=1.0, motion="pulse"),
                C("sign-yield", 360, 200, scale=0.95, motion="bob"),
                C("car-blue", 320, 360, motion="approach"),
                C("pedestrian", 520, 390, motion="cross-right"),
            ],
            objects=[O("Full stop behind the line", 650, 90)],
        ),
        _seg(
            lesson_id, 2,
            title="Warning signs",
            backdrop="freeway",
            camera="ken-burns",
            concept="Yellow diamonds warn — slow and prepare.",
            narration="Yellow diamond signs warn of curves, merges, pedestrians, school zones, and slippery roads. Slow and prepare to react.",
            cast=[
                C("sign-warning", 200, 180, scale=1.1, motion="pulse"),
                C("sign-curve", 700, 190, scale=0.85, motion="sway"),
                C("car-red", 420, 350, motion="drive"),
            ],
            objects=[O("React before the hazard", 40, 90)],
        ),
        _seg(
            lesson_id, 3,
            title="Guide and service signs",
            backdrop="freeway",
            camera="pull-out",
            concept="Green destinations, blue services, brown parks.",
            narration="Green signs guide routes and exits. Blue signs mark services. Brown signs mark parks and recreation.",
            cast=[
                C("sign-guide", 320, 160, scale=1.0, motion="bob"),
                C("car-blue", 200, 360, motion="drive"),
                C("car-red", 480, 350, motion="drive"),
                C("truck", 720, 320, scale=0.9, motion="drive"),
            ],
            objects=[O("Plan your lane early", 40, 90)],
        ),
        _seg(
            lesson_id, 4,
            title="Traffic signals",
            backdrop="intersection",
            camera="zoom-punch",
            concept="Flashing red equals a stop sign.",
            narration="Green means go if clear; yellow means prepare to stop; red means stop. Flashing red equals a stop sign.",
            cast=[
                C("traffic-light-red", 480, 120, scale=1.1, motion="flash"),
                C("car-red", 300, 360, motion="approach"),
                C("car-green", 650, 300, motion="cross-left", flip=True),
                C("pedestrian", 500, 400, motion="walk"),
            ],
            objects=[O("Flashing red = stop", 40, 80)],
        ),
        _seg(
            lesson_id, 5,
            title="Pavement markings",
            backdrop="freeway",
            camera="pan-right",
            concept="Solid yellow on your side means do not pass.",
            narration="Yellow lines separate opposite directions; white lines separate same-direction lanes. A solid line on your side means do not pass.",
            cast=[
                C("car-blue", 280, 340, motion="drive"),
                C("car-red", 520, 350, motion="drive"),
                C("car-green", 740, 340, scale=0.9, motion="drive"),
            ],
            objects=[O("Solid = stay put", 40, 90)],
        ),
        _seg(
            lesson_id, 6,
            title="Railroad crossings",
            backdrop="intersection",
            camera="zoom-punch",
            concept="Never drive around gates; exit stalled cars immediately.",
            narration="Never cross when lights flash or gates lower. If stalled on tracks, exit immediately and move away at an angle toward the oncoming train.",
            cast=[
                C("sign-rail", 200, 180, scale=1.05, motion="flash"),
                C("car-red", 360, 360, motion="approach"),
                C("sign-stop", 520, 200, scale=0.7),
            ],
            objects=[O("Gates down = stop", 650, 90)],
        ),
        _seg(
            lesson_id, 7,
            title="Roundabouts",
            backdrop="intersection",
            camera="pull-out",
            concept="Yield on entry; keep moving once inside.",
            narration="Yield to traffic already in the circle, enter when clear, and signal when exiting. Do not stop inside the circulating roadway.",
            cast=[
                C("sign-yield", 180, 200, scale=0.85, motion="pulse"),
                C("car-green", 300, 360, motion="drive"),
                C("car-blue", 560, 300, motion="cross-left", flip=True),
                C("bike", 700, 380, motion="cross-right"),
            ],
            objects=[O("Yield, then circulate", 40, 90)],
        ),
        _seg(
            lesson_id, 8,
            title="Parking clearances",
            backdrop="residential",
            camera="pan-left",
            concept="Respect hydrants, crosswalks, and colored curbs.",
            narration="Do not park too close to hydrants, crosswalks, stop signs, or driveways. Check local curb colors and posted restrictions.",
            cast=[
                C("car-white", 320, 340, motion="bob"),
                C("sign-stop", 160, 200, scale=0.75),
                C("pedestrian", 560, 360, motion="walk"),
            ],
            objects=[O("Read curb colors", 650, 90)],
        ),
        _seg(
            lesson_id, 9,
            title="Night headlights",
            backdrop="night-road",
            camera="ken-burns",
            concept="Dim high beams for oncoming traffic and when following.",
            narration="Use headlights from 30 minutes after sunset to 30 minutes before sunrise and whenever visibility is poor. Dim high beams for oncoming traffic.",
            cast=[
                C("car-blue", 300, 340, motion="drive"),
                C("car-red", 620, 350, scale=0.9, motion="drive", flip=True),
                C("sign-speed", 140, 190, scale=0.75),
            ],
            objects=[O("Dim for others", 700, 90)],
        ),
    ]


def build_dmv_sharing(lesson_id: str = "ca-dmv-permit-sharing") -> list[SegmentStoryboard]:
    return [
        _seg(
            lesson_id, 0,
            title="Pedestrians and bikes",
            backdrop="residential",
            camera="ken-burns",
            concept="Yield at crosswalks; give bikes three feet when passing.",
            narration="Pedestrians in crosswalks have the right of way. When passing a bicycle, leave at least three feet of space.",
            cast=[
                C("pedestrian", 460, 380, motion="cross-right"),
                C("bike", 300, 370, motion="drive"),
                C("car-blue", 600, 340, motion="drive"),
                C("sign-bike", 140, 190, scale=0.85, motion="pulse"),
            ],
            objects=[O("3-foot pass · yield to walkers", 40, 85)],
        ),
        _seg(
            lesson_id, 1,
            title="Motorcycle awareness",
            backdrop="freeway",
            camera="dolly-shake",
            concept="Look twice — motorcycles hide in blind spots.",
            narration="Motorcycles are easy to miss in blind spots. Give them a full lane and extra following distance. Double-check before lane changes.",
            cast=[
                C("motorcycle", 420, 360, motion="drive"),
                C("car-red", 200, 350, motion="drive"),
                C("car-blue", 680, 340, motion="drive"),
            ],
            objects=[O("Check blind spots twice", 40, 90)],
        ),
        _seg(
            lesson_id, 2,
            title="Large truck no-zones",
            backdrop="freeway",
            camera="pan-left",
            concept="If you cannot see their mirrors, they cannot see you.",
            narration="Trucks have large blind spots, long stopping distances, and wide turns. Do not cut in and brake; avoid lingering beside a truck.",
            cast=[
                C("truck", 400, 300, scale=1.15, motion="drive"),
                C("car-red", 200, 370, scale=0.85, motion="drive"),
                C("car-green", 720, 360, scale=0.85, motion="drive"),
            ],
            objects=[O("Stay out of no-zones", 40, 85), O("Wide turns", 700, 100)],
        ),
        _seg(
            lesson_id, 3,
            title="Freeway merging",
            backdrop="freeway",
            camera="pan-right",
            concept="Match speed on the ramp, then merge into a gap.",
            narration="Accelerate on the on-ramp to match traffic, signal, and merge when there is a gap. Use the left lane for passing, then return right.",
            cast=[
                C("car-green", 220, 360, motion="approach"),
                C("car-blue", 480, 340, motion="drive"),
                C("truck", 720, 310, scale=0.9, motion="drive"),
            ],
            objects=[O("Match speed, then merge", 40, 90)],
        ),
        _seg(
            lesson_id, 4,
            title="Weather and hydroplaning",
            backdrop="freeway",
            camera="dolly-shake",
            concept="Slow down; low beams in fog; ease off if you hydroplane.",
            narration="Slow down in rain and fog. Use low beams in fog. If you hydroplane, ease off the gas and steer straight until tires regain grip.",
            cast=[
                C("car-blue", 360, 340, motion="drive"),
                C("sign-warning", 160, 180, scale=0.9, motion="pulse"),
                C("car-red", 650, 350, scale=0.9, motion="drive"),
            ],
            objects=[O("Low beams in fog", 700, 90)],
        ),
        _seg(
            lesson_id, 5,
            title="Emergency vehicles",
            backdrop="freeway",
            camera="pan-right",
            concept="Pull right and stop for lights and sirens.",
            narration="Yield to emergency vehicles with lights and sirens by pulling to the right and stopping. Do not block intersections.",
            cast=[
                C("ambulance", 200, 320, scale=1.05, motion="drive"),
                C("car-blue", 520, 360, motion="drive"),
                C("car-green", 720, 350, scale=0.9, motion="drive"),
            ],
            objects=[O("Pull right & stop", 600, 90)],
        ),
        _seg(
            lesson_id, 6,
            title="Work zones",
            backdrop="work-zone",
            camera="dolly-shake",
            concept="Obey reduced speeds and flaggers; fines often double.",
            narration="Obey reduced work-zone speeds and flaggers. Fines often double in construction zones. Expect lane shifts and workers near traffic.",
            cast=[
                C("sign-work", 160, 190, scale=1.0, motion="pulse"),
                C("cone", 300, 400),
                C("cone", 360, 400),
                C("cone", 420, 400),
                C("truck", 560, 310, scale=0.9, motion="bob"),
                C("car-blue", 780, 350, scale=0.85, motion="drive"),
            ],
            objects=[O("Follow the flagger", 40, 90)],
        ),
        _seg(
            lesson_id, 7,
            title="Before you drive",
            backdrop="residential",
            camera="push-in",
            concept="Quick pre-drive check: brakes, lights, tires, mirrors, fuel.",
            narration="Check brakes, lights, tires, mirrors, and fuel. Adjust mirrors and seats before moving. Fix warning lights promptly.",
            cast=[
                C("car-red", 360, 340, scale=1.15, motion="bob"),
                C("adult", 520, 300, motion="sway"),
                C("teen", 580, 310, motion="bob"),
            ],
            objects=[O("Walk-around check", 40, 90)],
        ),
        _seg(
            lesson_id, 8,
            title="Handbook checkpoint",
            backdrop="residential",
            camera="static",
            concept="The official handbook overrides any study aid.",
            narration="Re-read the California Driver's Handbook sections on signs, sharing the road, and special driving situations. Official wording beats any study aid.",
            cast=[
                C("adult", 400, 300, motion="bob"),
                C("teen", 480, 310, motion="sway"),
                C("sign-stop", 200, 200, scale=0.7),
            ],
            objects=[O("Handbook = authority", 650, 90)],
        ),
        _seg(
            lesson_id, 9,
            title="Practice test habit",
            backdrop="school-zone",
            camera="pull-out",
            concept="Short blocks plus quizzes beat cramming.",
            narration="Take short CA DMV practice quizzes after each 15 to 20 minute study block. Come back later instead of cramming for hours.",
            cast=[
                C("teen", 420, 300, motion="bob"),
                C("car-green", 280, 350, motion="drive"),
                C("sign-school", 700, 200, scale=0.8),
            ],
            objects=[O("Quiz after each block", 40, 90)],
        ),
    ]


def dmv_basics_segments() -> list[SegmentStoryboard]:
    return build_dmv_basics()


def dmv_signs_segments() -> list[SegmentStoryboard]:
    return build_dmv_signs()


def dmv_sharing_segments() -> list[SegmentStoryboard]:
    return build_dmv_sharing()
